// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoComments.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

public interface ClientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Client)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string manufacturer = 12;</code>
   * @return The manufacturer.
   */
  String getManufacturer();
  /**
   * <code>string manufacturer = 12;</code>
   * @return The bytes for manufacturer.
   */
  com.google.protobuf.ByteString
      getManufacturerBytes();

  /**
   * <code>string model = 13;</code>
   * @return The model.
   */
  String getModel();
  /**
   * <code>string model = 13;</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>string system = 18;</code>
   * @return The system.
   */
  String getSystem();
  /**
   * <code>string system = 18;</code>
   * @return The bytes for system.
   */
  com.google.protobuf.ByteString
      getSystemBytes();

  /**
   * <code>string sysVersion = 19;</code>
   * @return The sysVersion.
   */
  String getSysVersion();
  /**
   * <code>string sysVersion = 19;</code>
   * @return The bytes for sysVersion.
   */
  com.google.protobuf.ByteString
      getSysVersionBytes();

  /**
   * <code>string language = 21;</code>
   * @return The language.
   */
  String getLanguage();
  /**
   * <code>string language = 21;</code>
   * @return The bytes for language.
   */
  com.google.protobuf.ByteString
      getLanguageBytes();

  /**
   * <code>string country = 22;</code>
   * @return The country.
   */
  String getCountry();
  /**
   * <code>string country = 22;</code>
   * @return The bytes for country.
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>string timeZone = 80;</code>
   * @return The timeZone.
   */
  String getTimeZone();
  /**
   * <code>string timeZone = 80;</code>
   * @return The bytes for timeZone.
   */
  com.google.protobuf.ByteString
      getTimeZoneBytes();

  /**
   * <code>string brand = 98;</code>
   * @return The brand.
   */
  String getBrand();
  /**
   * <code>string brand = 98;</code>
   * @return The bytes for brand.
   */
  com.google.protobuf.ByteString
      getBrandBytes();
}
