// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoComments.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

public interface CommentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Comment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Content content = 2;</code>
   * @return Whether the content field is set.
   */
  boolean hasContent();
  /**
   * <code>.Content content = 2;</code>
   * @return The content.
   */
  Content getContent();
  /**
   * <code>.Content content = 2;</code>
   */
  ContentOrBuilder getContentOrBuilder();

  /**
   * <code>.User user = 3;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.User user = 3;</code>
   * @return The user.
   */
  User getUser();
  /**
   * <code>.User user = 3;</code>
   */
  UserOrBuilder getUserOrBuilder();
}
