// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoComments.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

public interface ContinuationItemsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ContinuationItems)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ContinuationItem continuationItem = 1;</code>
   */
  java.util.List<ContinuationItem>
      getContinuationItemList();
  /**
   * <code>repeated .ContinuationItem continuationItem = 1;</code>
   */
  ContinuationItem getContinuationItem(int index);
  /**
   * <code>repeated .ContinuationItem continuationItem = 1;</code>
   */
  int getContinuationItemCount();
  /**
   * <code>repeated .ContinuationItem continuationItem = 1;</code>
   */
  java.util.List<? extends ContinuationItemOrBuilder>
      getContinuationItemOrBuilderList();
  /**
   * <code>repeated .ContinuationItem continuationItem = 1;</code>
   */
  ContinuationItemOrBuilder getContinuationItemOrBuilder(
      int index);
}
