// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoComments.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

public interface ContinuationItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ContinuationItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.UNK3 unk3 = 3;</code>
   * @return Whether the unk3 field is set.
   */
  boolean hasUnk3();
  /**
   * <code>.UNK3 unk3 = 3;</code>
   * @return The unk3.
   */
  UNK3 getUnk3();
  /**
   * <code>.UNK3 unk3 = 3;</code>
   */
  UNK3OrBuilder getUnk3OrBuilder();
}
