// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoComments.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

/**
 * Protobuf type {@code ContinuationItemsAction777}
 */
public final class ContinuationItemsAction777 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ContinuationItemsAction777)
    ContinuationItemsAction777OrBuilder {
private static final long serialVersionUID = 0L;
  // Use ContinuationItemsAction777.newBuilder() to construct.
  private ContinuationItemsAction777(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ContinuationItemsAction777() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ContinuationItemsAction777();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return YTVideoComments.internal_static_ContinuationItemsAction777_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return YTVideoComments.internal_static_ContinuationItemsAction777_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ContinuationItemsAction777.class, Builder.class);
  }

  public static final int CONTINUATIONITEMS_FIELD_NUMBER = 1;
  private ContinuationItems continuationItems_;
  /**
   * <code>.ContinuationItems continuationItems = 1;</code>
   * @return Whether the continuationItems field is set.
   */
  @Override
  public boolean hasContinuationItems() {
    return continuationItems_ != null;
  }
  /**
   * <code>.ContinuationItems continuationItems = 1;</code>
   * @return The continuationItems.
   */
  @Override
  public ContinuationItems getContinuationItems() {
    return continuationItems_ == null ? ContinuationItems.getDefaultInstance() : continuationItems_;
  }
  /**
   * <code>.ContinuationItems continuationItems = 1;</code>
   */
  @Override
  public ContinuationItemsOrBuilder getContinuationItemsOrBuilder() {
    return continuationItems_ == null ? ContinuationItems.getDefaultInstance() : continuationItems_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (continuationItems_ != null) {
      output.writeMessage(1, getContinuationItems());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (continuationItems_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getContinuationItems());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ContinuationItemsAction777)) {
      return super.equals(obj);
    }
    ContinuationItemsAction777 other = (ContinuationItemsAction777) obj;

    if (hasContinuationItems() != other.hasContinuationItems()) return false;
    if (hasContinuationItems()) {
      if (!getContinuationItems()
          .equals(other.getContinuationItems())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasContinuationItems()) {
      hash = (37 * hash) + CONTINUATIONITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getContinuationItems().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ContinuationItemsAction777 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ContinuationItemsAction777 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ContinuationItemsAction777 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ContinuationItemsAction777 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ContinuationItemsAction777 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ContinuationItemsAction777 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ContinuationItemsAction777 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ContinuationItemsAction777 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ContinuationItemsAction777 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ContinuationItemsAction777 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ContinuationItemsAction777 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ContinuationItemsAction777 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ContinuationItemsAction777 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ContinuationItemsAction777}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ContinuationItemsAction777)
      ContinuationItemsAction777OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return YTVideoComments.internal_static_ContinuationItemsAction777_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return YTVideoComments.internal_static_ContinuationItemsAction777_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ContinuationItemsAction777.class, Builder.class);
    }

    // Construct using icu.freedomintrovert.YTSendCommAntiFraud.grpcApi.ContinuationItemsAction777.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      continuationItems_ = null;
      if (continuationItemsBuilder_ != null) {
        continuationItemsBuilder_.dispose();
        continuationItemsBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return YTVideoComments.internal_static_ContinuationItemsAction777_descriptor;
    }

    @Override
    public ContinuationItemsAction777 getDefaultInstanceForType() {
      return ContinuationItemsAction777.getDefaultInstance();
    }

    @Override
    public ContinuationItemsAction777 build() {
      ContinuationItemsAction777 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ContinuationItemsAction777 buildPartial() {
      ContinuationItemsAction777 result = new ContinuationItemsAction777(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ContinuationItemsAction777 result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.continuationItems_ = continuationItemsBuilder_ == null
            ? continuationItems_
            : continuationItemsBuilder_.build();
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ContinuationItemsAction777) {
        return mergeFrom((ContinuationItemsAction777)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ContinuationItemsAction777 other) {
      if (other == ContinuationItemsAction777.getDefaultInstance()) return this;
      if (other.hasContinuationItems()) {
        mergeContinuationItems(other.getContinuationItems());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getContinuationItemsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private ContinuationItems continuationItems_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ContinuationItems, ContinuationItems.Builder, ContinuationItemsOrBuilder> continuationItemsBuilder_;
    /**
     * <code>.ContinuationItems continuationItems = 1;</code>
     * @return Whether the continuationItems field is set.
     */
    public boolean hasContinuationItems() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.ContinuationItems continuationItems = 1;</code>
     * @return The continuationItems.
     */
    public ContinuationItems getContinuationItems() {
      if (continuationItemsBuilder_ == null) {
        return continuationItems_ == null ? ContinuationItems.getDefaultInstance() : continuationItems_;
      } else {
        return continuationItemsBuilder_.getMessage();
      }
    }
    /**
     * <code>.ContinuationItems continuationItems = 1;</code>
     */
    public Builder setContinuationItems(ContinuationItems value) {
      if (continuationItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        continuationItems_ = value;
      } else {
        continuationItemsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ContinuationItems continuationItems = 1;</code>
     */
    public Builder setContinuationItems(
        ContinuationItems.Builder builderForValue) {
      if (continuationItemsBuilder_ == null) {
        continuationItems_ = builderForValue.build();
      } else {
        continuationItemsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ContinuationItems continuationItems = 1;</code>
     */
    public Builder mergeContinuationItems(ContinuationItems value) {
      if (continuationItemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          continuationItems_ != null &&
          continuationItems_ != ContinuationItems.getDefaultInstance()) {
          getContinuationItemsBuilder().mergeFrom(value);
        } else {
          continuationItems_ = value;
        }
      } else {
        continuationItemsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ContinuationItems continuationItems = 1;</code>
     */
    public Builder clearContinuationItems() {
      bitField0_ = (bitField0_ & ~0x00000001);
      continuationItems_ = null;
      if (continuationItemsBuilder_ != null) {
        continuationItemsBuilder_.dispose();
        continuationItemsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.ContinuationItems continuationItems = 1;</code>
     */
    public ContinuationItems.Builder getContinuationItemsBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getContinuationItemsFieldBuilder().getBuilder();
    }
    /**
     * <code>.ContinuationItems continuationItems = 1;</code>
     */
    public ContinuationItemsOrBuilder getContinuationItemsOrBuilder() {
      if (continuationItemsBuilder_ != null) {
        return continuationItemsBuilder_.getMessageOrBuilder();
      } else {
        return continuationItems_ == null ?
            ContinuationItems.getDefaultInstance() : continuationItems_;
      }
    }
    /**
     * <code>.ContinuationItems continuationItems = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ContinuationItems, ContinuationItems.Builder, ContinuationItemsOrBuilder>
        getContinuationItemsFieldBuilder() {
      if (continuationItemsBuilder_ == null) {
        continuationItemsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ContinuationItems, ContinuationItems.Builder, ContinuationItemsOrBuilder>(
                getContinuationItems(),
                getParentForChildren(),
                isClean());
        continuationItems_ = null;
      }
      return continuationItemsBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ContinuationItemsAction777)
  }

  // @@protoc_insertion_point(class_scope:ContinuationItemsAction777)
  private static final ContinuationItemsAction777 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ContinuationItemsAction777();
  }

  public static ContinuationItemsAction777 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ContinuationItemsAction777>
      PARSER = new com.google.protobuf.AbstractParser<ContinuationItemsAction777>() {
    @Override
    public ContinuationItemsAction777 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ContinuationItemsAction777> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ContinuationItemsAction777> getParserForType() {
    return PARSER;
  }

  @Override
  public ContinuationItemsAction777 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

