// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendComment.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

/**
 * Protobuf type {@code CreatCommentResponse}
 */
public final class CreatCommentResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CreatCommentResponse)
    CreatCommentResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreatCommentResponse.newBuilder() to construct.
  private CreatCommentResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreatCommentResponse() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreatCommentResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CreatComment.internal_static_CreatCommentResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CreatComment.internal_static_CreatCommentResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CreatCommentResponse.class, Builder.class);
  }

  public static final int ACTIONS_FIELD_NUMBER = 4;
  private Actions actions_;
  /**
   * <code>.Actions actions = 4;</code>
   * @return Whether the actions field is set.
   */
  @Override
  public boolean hasActions() {
    return actions_ != null;
  }
  /**
   * <code>.Actions actions = 4;</code>
   * @return The actions.
   */
  @Override
  public Actions getActions() {
    return actions_ == null ? Actions.getDefaultInstance() : actions_;
  }
  /**
   * <code>.Actions actions = 4;</code>
   */
  @Override
  public ActionsOrBuilder getActionsOrBuilder() {
    return actions_ == null ? Actions.getDefaultInstance() : actions_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (actions_ != null) {
      output.writeMessage(4, getActions());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (actions_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getActions());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CreatCommentResponse)) {
      return super.equals(obj);
    }
    CreatCommentResponse other = (CreatCommentResponse) obj;

    if (hasActions() != other.hasActions()) return false;
    if (hasActions()) {
      if (!getActions()
          .equals(other.getActions())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasActions()) {
      hash = (37 * hash) + ACTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getActions().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CreatCommentResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CreatCommentResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CreatCommentResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CreatCommentResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CreatCommentResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CreatCommentResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CreatCommentResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CreatCommentResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CreatCommentResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CreatCommentResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CreatCommentResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CreatCommentResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CreatCommentResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CreatCommentResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CreatCommentResponse)
      CreatCommentResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CreatComment.internal_static_CreatCommentResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CreatComment.internal_static_CreatCommentResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CreatCommentResponse.class, Builder.class);
    }

    // Construct using icu.freedomintrovert.YTSendCommAntiFraud.grpcApi.CreatCommentResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      actions_ = null;
      if (actionsBuilder_ != null) {
        actionsBuilder_.dispose();
        actionsBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CreatComment.internal_static_CreatCommentResponse_descriptor;
    }

    @Override
    public CreatCommentResponse getDefaultInstanceForType() {
      return CreatCommentResponse.getDefaultInstance();
    }

    @Override
    public CreatCommentResponse build() {
      CreatCommentResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CreatCommentResponse buildPartial() {
      CreatCommentResponse result = new CreatCommentResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(CreatCommentResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.actions_ = actionsBuilder_ == null
            ? actions_
            : actionsBuilder_.build();
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CreatCommentResponse) {
        return mergeFrom((CreatCommentResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CreatCommentResponse other) {
      if (other == CreatCommentResponse.getDefaultInstance()) return this;
      if (other.hasActions()) {
        mergeActions(other.getActions());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 34: {
              input.readMessage(
                  getActionsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Actions actions_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Actions, Actions.Builder, ActionsOrBuilder> actionsBuilder_;
    /**
     * <code>.Actions actions = 4;</code>
     * @return Whether the actions field is set.
     */
    public boolean hasActions() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Actions actions = 4;</code>
     * @return The actions.
     */
    public Actions getActions() {
      if (actionsBuilder_ == null) {
        return actions_ == null ? Actions.getDefaultInstance() : actions_;
      } else {
        return actionsBuilder_.getMessage();
      }
    }
    /**
     * <code>.Actions actions = 4;</code>
     */
    public Builder setActions(Actions value) {
      if (actionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        actions_ = value;
      } else {
        actionsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Actions actions = 4;</code>
     */
    public Builder setActions(
        Actions.Builder builderForValue) {
      if (actionsBuilder_ == null) {
        actions_ = builderForValue.build();
      } else {
        actionsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Actions actions = 4;</code>
     */
    public Builder mergeActions(Actions value) {
      if (actionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          actions_ != null &&
          actions_ != Actions.getDefaultInstance()) {
          getActionsBuilder().mergeFrom(value);
        } else {
          actions_ = value;
        }
      } else {
        actionsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Actions actions = 4;</code>
     */
    public Builder clearActions() {
      bitField0_ = (bitField0_ & ~0x00000001);
      actions_ = null;
      if (actionsBuilder_ != null) {
        actionsBuilder_.dispose();
        actionsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Actions actions = 4;</code>
     */
    public Actions.Builder getActionsBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getActionsFieldBuilder().getBuilder();
    }
    /**
     * <code>.Actions actions = 4;</code>
     */
    public ActionsOrBuilder getActionsOrBuilder() {
      if (actionsBuilder_ != null) {
        return actionsBuilder_.getMessageOrBuilder();
      } else {
        return actions_ == null ?
            Actions.getDefaultInstance() : actions_;
      }
    }
    /**
     * <code>.Actions actions = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Actions, Actions.Builder, ActionsOrBuilder>
        getActionsFieldBuilder() {
      if (actionsBuilder_ == null) {
        actionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Actions, Actions.Builder, ActionsOrBuilder>(
                getActions(),
                getParentForChildren(),
                isClean());
        actions_ = null;
      }
      return actionsBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CreatCommentResponse)
  }

  // @@protoc_insertion_point(class_scope:CreatCommentResponse)
  private static final CreatCommentResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CreatCommentResponse();
  }

  public static CreatCommentResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreatCommentResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreatCommentResponse>() {
    @Override
    public CreatCommentResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreatCommentResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CreatCommentResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public CreatCommentResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

