// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendComment.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

/**
 * Protobuf type {@code CreatCommentRequest}
 */
public final class CreatCommentRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CreatCommentRequest)
    CreatCommentRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreatCommentRequest.newBuilder() to construct.
  private CreatCommentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreatCommentRequest() {
    videoInfoProtoBase64_ = "";
    commentText_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreatCommentRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CreatComment.internal_static_CreatCommentRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CreatComment.internal_static_CreatCommentRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CreatCommentRequest.class, Builder.class);
  }

  public static final int CONTEXT1_FIELD_NUMBER = 1;
  private Context1 context1_;
  /**
   * <code>.Context1 context1 = 1;</code>
   * @return Whether the context1 field is set.
   */
  @Override
  public boolean hasContext1() {
    return context1_ != null;
  }
  /**
   * <code>.Context1 context1 = 1;</code>
   * @return The context1.
   */
  @Override
  public Context1 getContext1() {
    return context1_ == null ? Context1.getDefaultInstance() : context1_;
  }
  /**
   * <code>.Context1 context1 = 1;</code>
   */
  @Override
  public Context1OrBuilder getContext1OrBuilder() {
    return context1_ == null ? Context1.getDefaultInstance() : context1_;
  }

  public static final int VIDEOINFOPROTOBASE64_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object videoInfoProtoBase64_ = "";
  /**
   * <code>string videoInfoProtoBase64 = 2;</code>
   * @return The videoInfoProtoBase64.
   */
  @Override
  public String getVideoInfoProtoBase64() {
    Object ref = videoInfoProtoBase64_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      videoInfoProtoBase64_ = s;
      return s;
    }
  }
  /**
   * <code>string videoInfoProtoBase64 = 2;</code>
   * @return The bytes for videoInfoProtoBase64.
   */
  @Override
  public com.google.protobuf.ByteString
      getVideoInfoProtoBase64Bytes() {
    Object ref = videoInfoProtoBase64_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      videoInfoProtoBase64_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMENTTEXT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object commentText_ = "";
  /**
   * <code>string commentText = 3;</code>
   * @return The commentText.
   */
  @Override
  public String getCommentText() {
    Object ref = commentText_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      commentText_ = s;
      return s;
    }
  }
  /**
   * <code>string commentText = 3;</code>
   * @return The bytes for commentText.
   */
  @Override
  public com.google.protobuf.ByteString
      getCommentTextBytes() {
    Object ref = commentText_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      commentText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UNKNOWNINT_17_FIELD_NUMBER = 17;
  private int unknownInt17_ = 0;
  /**
   * <code>int32 unknownInt_17 = 17;</code>
   * @return The unknownInt17.
   */
  @Override
  public int getUnknownInt17() {
    return unknownInt17_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (context1_ != null) {
      output.writeMessage(1, getContext1());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(videoInfoProtoBase64_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, videoInfoProtoBase64_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commentText_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, commentText_);
    }
    if (unknownInt17_ != 0) {
      output.writeInt32(17, unknownInt17_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (context1_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getContext1());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(videoInfoProtoBase64_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, videoInfoProtoBase64_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commentText_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, commentText_);
    }
    if (unknownInt17_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(17, unknownInt17_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CreatCommentRequest)) {
      return super.equals(obj);
    }
    CreatCommentRequest other = (CreatCommentRequest) obj;

    if (hasContext1() != other.hasContext1()) return false;
    if (hasContext1()) {
      if (!getContext1()
          .equals(other.getContext1())) return false;
    }
    if (!getVideoInfoProtoBase64()
        .equals(other.getVideoInfoProtoBase64())) return false;
    if (!getCommentText()
        .equals(other.getCommentText())) return false;
    if (getUnknownInt17()
        != other.getUnknownInt17()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasContext1()) {
      hash = (37 * hash) + CONTEXT1_FIELD_NUMBER;
      hash = (53 * hash) + getContext1().hashCode();
    }
    hash = (37 * hash) + VIDEOINFOPROTOBASE64_FIELD_NUMBER;
    hash = (53 * hash) + getVideoInfoProtoBase64().hashCode();
    hash = (37 * hash) + COMMENTTEXT_FIELD_NUMBER;
    hash = (53 * hash) + getCommentText().hashCode();
    hash = (37 * hash) + UNKNOWNINT_17_FIELD_NUMBER;
    hash = (53 * hash) + getUnknownInt17();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CreatCommentRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CreatCommentRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CreatCommentRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CreatCommentRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CreatCommentRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CreatCommentRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CreatCommentRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CreatCommentRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CreatCommentRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CreatCommentRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CreatCommentRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CreatCommentRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CreatCommentRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CreatCommentRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CreatCommentRequest)
      CreatCommentRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CreatComment.internal_static_CreatCommentRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CreatComment.internal_static_CreatCommentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CreatCommentRequest.class, Builder.class);
    }

    // Construct using icu.freedomintrovert.YTSendCommAntiFraud.grpcApi.CreatCommentRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      context1_ = null;
      if (context1Builder_ != null) {
        context1Builder_.dispose();
        context1Builder_ = null;
      }
      videoInfoProtoBase64_ = "";
      commentText_ = "";
      unknownInt17_ = 0;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CreatComment.internal_static_CreatCommentRequest_descriptor;
    }

    @Override
    public CreatCommentRequest getDefaultInstanceForType() {
      return CreatCommentRequest.getDefaultInstance();
    }

    @Override
    public CreatCommentRequest build() {
      CreatCommentRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CreatCommentRequest buildPartial() {
      CreatCommentRequest result = new CreatCommentRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(CreatCommentRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.context1_ = context1Builder_ == null
            ? context1_
            : context1Builder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.videoInfoProtoBase64_ = videoInfoProtoBase64_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.commentText_ = commentText_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.unknownInt17_ = unknownInt17_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CreatCommentRequest) {
        return mergeFrom((CreatCommentRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CreatCommentRequest other) {
      if (other == CreatCommentRequest.getDefaultInstance()) return this;
      if (other.hasContext1()) {
        mergeContext1(other.getContext1());
      }
      if (!other.getVideoInfoProtoBase64().isEmpty()) {
        videoInfoProtoBase64_ = other.videoInfoProtoBase64_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getCommentText().isEmpty()) {
        commentText_ = other.commentText_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getUnknownInt17() != 0) {
        setUnknownInt17(other.getUnknownInt17());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getContext1FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              videoInfoProtoBase64_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              commentText_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 136: {
              unknownInt17_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 136
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Context1 context1_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Context1, Context1.Builder, Context1OrBuilder> context1Builder_;
    /**
     * <code>.Context1 context1 = 1;</code>
     * @return Whether the context1 field is set.
     */
    public boolean hasContext1() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Context1 context1 = 1;</code>
     * @return The context1.
     */
    public Context1 getContext1() {
      if (context1Builder_ == null) {
        return context1_ == null ? Context1.getDefaultInstance() : context1_;
      } else {
        return context1Builder_.getMessage();
      }
    }
    /**
     * <code>.Context1 context1 = 1;</code>
     */
    public Builder setContext1(Context1 value) {
      if (context1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        context1_ = value;
      } else {
        context1Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Context1 context1 = 1;</code>
     */
    public Builder setContext1(
        Context1.Builder builderForValue) {
      if (context1Builder_ == null) {
        context1_ = builderForValue.build();
      } else {
        context1Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Context1 context1 = 1;</code>
     */
    public Builder mergeContext1(Context1 value) {
      if (context1Builder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          context1_ != null &&
          context1_ != Context1.getDefaultInstance()) {
          getContext1Builder().mergeFrom(value);
        } else {
          context1_ = value;
        }
      } else {
        context1Builder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Context1 context1 = 1;</code>
     */
    public Builder clearContext1() {
      bitField0_ = (bitField0_ & ~0x00000001);
      context1_ = null;
      if (context1Builder_ != null) {
        context1Builder_.dispose();
        context1Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Context1 context1 = 1;</code>
     */
    public Context1.Builder getContext1Builder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getContext1FieldBuilder().getBuilder();
    }
    /**
     * <code>.Context1 context1 = 1;</code>
     */
    public Context1OrBuilder getContext1OrBuilder() {
      if (context1Builder_ != null) {
        return context1Builder_.getMessageOrBuilder();
      } else {
        return context1_ == null ?
            Context1.getDefaultInstance() : context1_;
      }
    }
    /**
     * <code>.Context1 context1 = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Context1, Context1.Builder, Context1OrBuilder>
        getContext1FieldBuilder() {
      if (context1Builder_ == null) {
        context1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Context1, Context1.Builder, Context1OrBuilder>(
                getContext1(),
                getParentForChildren(),
                isClean());
        context1_ = null;
      }
      return context1Builder_;
    }

    private Object videoInfoProtoBase64_ = "";
    /**
     * <code>string videoInfoProtoBase64 = 2;</code>
     * @return The videoInfoProtoBase64.
     */
    public String getVideoInfoProtoBase64() {
      Object ref = videoInfoProtoBase64_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        videoInfoProtoBase64_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string videoInfoProtoBase64 = 2;</code>
     * @return The bytes for videoInfoProtoBase64.
     */
    public com.google.protobuf.ByteString
        getVideoInfoProtoBase64Bytes() {
      Object ref = videoInfoProtoBase64_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        videoInfoProtoBase64_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string videoInfoProtoBase64 = 2;</code>
     * @param value The videoInfoProtoBase64 to set.
     * @return This builder for chaining.
     */
    public Builder setVideoInfoProtoBase64(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      videoInfoProtoBase64_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string videoInfoProtoBase64 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVideoInfoProtoBase64() {
      videoInfoProtoBase64_ = getDefaultInstance().getVideoInfoProtoBase64();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string videoInfoProtoBase64 = 2;</code>
     * @param value The bytes for videoInfoProtoBase64 to set.
     * @return This builder for chaining.
     */
    public Builder setVideoInfoProtoBase64Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      videoInfoProtoBase64_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private Object commentText_ = "";
    /**
     * <code>string commentText = 3;</code>
     * @return The commentText.
     */
    public String getCommentText() {
      Object ref = commentText_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        commentText_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string commentText = 3;</code>
     * @return The bytes for commentText.
     */
    public com.google.protobuf.ByteString
        getCommentTextBytes() {
      Object ref = commentText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        commentText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string commentText = 3;</code>
     * @param value The commentText to set.
     * @return This builder for chaining.
     */
    public Builder setCommentText(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      commentText_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string commentText = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommentText() {
      commentText_ = getDefaultInstance().getCommentText();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string commentText = 3;</code>
     * @param value The bytes for commentText to set.
     * @return This builder for chaining.
     */
    public Builder setCommentTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      commentText_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int unknownInt17_ ;
    /**
     * <code>int32 unknownInt_17 = 17;</code>
     * @return The unknownInt17.
     */
    @Override
    public int getUnknownInt17() {
      return unknownInt17_;
    }
    /**
     * <code>int32 unknownInt_17 = 17;</code>
     * @param value The unknownInt17 to set.
     * @return This builder for chaining.
     */
    public Builder setUnknownInt17(int value) {

      unknownInt17_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 unknownInt_17 = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnknownInt17() {
      bitField0_ = (bitField0_ & ~0x00000008);
      unknownInt17_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CreatCommentRequest)
  }

  // @@protoc_insertion_point(class_scope:CreatCommentRequest)
  private static final CreatCommentRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CreatCommentRequest();
  }

  public static CreatCommentRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreatCommentRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreatCommentRequest>() {
    @Override
    public CreatCommentRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreatCommentRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CreatCommentRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public CreatCommentRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

