// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendComment.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

public final class CreatComment {
  private CreatComment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreatCommentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreatCommentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Context1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Context1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreatCommentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreatCommentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Actions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Actions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RunAttestationCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RunAttestationCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ids_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ids_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021SendComment.proto\"|\n\023CreatCommentReque" +
      "st\022\033\n\010context1\030\001 \001(\0132\t.Context1\022\034\n\024video" +
      "InfoProtoBase64\030\002 \001(\t\022\023\n\013commentText\030\003 \001" +
      "(\t\022\025\n\runknownInt_17\030\021 \001(\005\"\n\n\010Context1\"1\n" +
      "\024CreatCommentResponse\022\031\n\007actions\030\004 \001(\0132\010" +
      ".Actions\"D\n\007Actions\0229\n\025runAttestationCom" +
      "mand\030\304\250\367\201\001 \001(\0132\026.RunAttestationCommand\"*" +
      "\n\025RunAttestationCommand\022\021\n\003ids\030\001 \003(\0132\004.I" +
      "ds\"M\n\003Ids\022\021\n\tcommentId\030\003 \001(\t\022\030\n\020encrypte" +
      "dVideoId\030\010 \001(\t\022\031\n\021externalChannelId\030\002 \001(" +
      "\tBB\n0icu.freedomintrovert.YTSendCommAnti" +
      "Fraud.grpcApiB\014CreatCommentP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CreatCommentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreatCommentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreatCommentRequest_descriptor,
        new String[] { "Context1", "VideoInfoProtoBase64", "CommentText", "UnknownInt17", });
    internal_static_Context1_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Context1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Context1_descriptor,
        new String[] { });
    internal_static_CreatCommentResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CreatCommentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreatCommentResponse_descriptor,
        new String[] { "Actions", });
    internal_static_Actions_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Actions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Actions_descriptor,
        new String[] { "RunAttestationCommand", });
    internal_static_RunAttestationCommand_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_RunAttestationCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RunAttestationCommand_descriptor,
        new String[] { "Ids", });
    internal_static_Ids_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Ids_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ids_descriptor,
        new String[] { "CommentId", "EncryptedVideoId", "ExternalChannelId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
