// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendComment.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

public interface CreatCommentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreatCommentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Actions actions = 4;</code>
   * @return Whether the actions field is set.
   */
  boolean hasActions();
  /**
   * <code>.Actions actions = 4;</code>
   * @return The actions.
   */
  Actions getActions();
  /**
   * <code>.Actions actions = 4;</code>
   */
  ActionsOrBuilder getActionsOrBuilder();
}
