// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendComment.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

public interface IdsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ids)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string commentId = 3;</code>
   * @return The commentId.
   */
  String getCommentId();
  /**
   * <code>string commentId = 3;</code>
   * @return The bytes for commentId.
   */
  com.google.protobuf.ByteString
      getCommentIdBytes();

  /**
   * <code>string encryptedVideoId = 8;</code>
   * @return The encryptedVideoId.
   */
  String getEncryptedVideoId();
  /**
   * <code>string encryptedVideoId = 8;</code>
   * @return The bytes for encryptedVideoId.
   */
  com.google.protobuf.ByteString
      getEncryptedVideoIdBytes();

  /**
   * <code>string externalChannelId = 2;</code>
   * @return The externalChannelId.
   */
  String getExternalChannelId();
  /**
   * <code>string externalChannelId = 2;</code>
   * @return The bytes for externalChannelId.
   */
  com.google.protobuf.ByteString
      getExternalChannelIdBytes();
}
