// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoComments.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

public interface MsgU1_6OrBuilder extends
    // @@protoc_insertion_point(interface_extends:MsgU1_6)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.MsgU1_6.MsgU1_6_2 msgu1_6_2 = 2;</code>
   * @return Whether the msgu162 field is set.
   */
  boolean hasMsgu162();
  /**
   * <code>.MsgU1_6.MsgU1_6_2 msgu1_6_2 = 2;</code>
   * @return The msgu162.
   */
  MsgU1_6.MsgU1_6_2 getMsgu162();
  /**
   * <code>.MsgU1_6.MsgU1_6_2 msgu1_6_2 = 2;</code>
   */
  MsgU1_6.MsgU1_6_2OrBuilder getMsgu162OrBuilder();
}
