// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoComments.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

/**
 * Protobuf type {@code NextInfo8}
 */
public final class NextInfo8 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:NextInfo8)
    NextInfo8OrBuilder {
private static final long serialVersionUID = 0L;
  // Use NextInfo8.newBuilder() to construct.
  private NextInfo8(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NextInfo8() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new NextInfo8();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return YTVideoComments.internal_static_NextInfo8_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return YTVideoComments.internal_static_NextInfo8_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            NextInfo8.class, Builder.class);
  }

  public static final int UNKMSG49399797_FIELD_NUMBER = 49399797;
  private UnkMsg49399797 unkMsg49399797_;
  /**
   * <code>.UnkMsg49399797 unkMsg49399797 = 49399797;</code>
   * @return Whether the unkMsg49399797 field is set.
   */
  @Override
  public boolean hasUnkMsg49399797() {
    return unkMsg49399797_ != null;
  }
  /**
   * <code>.UnkMsg49399797 unkMsg49399797 = 49399797;</code>
   * @return The unkMsg49399797.
   */
  @Override
  public UnkMsg49399797 getUnkMsg49399797() {
    return unkMsg49399797_ == null ? UnkMsg49399797.getDefaultInstance() : unkMsg49399797_;
  }
  /**
   * <code>.UnkMsg49399797 unkMsg49399797 = 49399797;</code>
   */
  @Override
  public UnkMsg49399797OrBuilder getUnkMsg49399797OrBuilder() {
    return unkMsg49399797_ == null ? UnkMsg49399797.getDefaultInstance() : unkMsg49399797_;
  }

  public static final int UNKMSG50195462_FIELD_NUMBER = 50195462;
  private UnkMsg50195462 unkMsg50195462_;
  /**
   * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
   * @return Whether the unkMsg50195462 field is set.
   */
  @Override
  public boolean hasUnkMsg50195462() {
    return unkMsg50195462_ != null;
  }
  /**
   * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
   * @return The unkMsg50195462.
   */
  @Override
  public UnkMsg50195462 getUnkMsg50195462() {
    return unkMsg50195462_ == null ? UnkMsg50195462.getDefaultInstance() : unkMsg50195462_;
  }
  /**
   * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
   */
  @Override
  public UnkMsg50195462OrBuilder getUnkMsg50195462OrBuilder() {
    return unkMsg50195462_ == null ? UnkMsg50195462.getDefaultInstance() : unkMsg50195462_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (unkMsg49399797_ != null) {
      output.writeMessage(49399797, getUnkMsg49399797());
    }
    if (unkMsg50195462_ != null) {
      output.writeMessage(50195462, getUnkMsg50195462());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (unkMsg49399797_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(49399797, getUnkMsg49399797());
    }
    if (unkMsg50195462_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(50195462, getUnkMsg50195462());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof NextInfo8)) {
      return super.equals(obj);
    }
    NextInfo8 other = (NextInfo8) obj;

    if (hasUnkMsg49399797() != other.hasUnkMsg49399797()) return false;
    if (hasUnkMsg49399797()) {
      if (!getUnkMsg49399797()
          .equals(other.getUnkMsg49399797())) return false;
    }
    if (hasUnkMsg50195462() != other.hasUnkMsg50195462()) return false;
    if (hasUnkMsg50195462()) {
      if (!getUnkMsg50195462()
          .equals(other.getUnkMsg50195462())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUnkMsg49399797()) {
      hash = (37 * hash) + UNKMSG49399797_FIELD_NUMBER;
      hash = (53 * hash) + getUnkMsg49399797().hashCode();
    }
    if (hasUnkMsg50195462()) {
      hash = (37 * hash) + UNKMSG50195462_FIELD_NUMBER;
      hash = (53 * hash) + getUnkMsg50195462().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static NextInfo8 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NextInfo8 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NextInfo8 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NextInfo8 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NextInfo8 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NextInfo8 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NextInfo8 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NextInfo8 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static NextInfo8 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static NextInfo8 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static NextInfo8 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NextInfo8 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(NextInfo8 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code NextInfo8}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NextInfo8)
      NextInfo8OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return YTVideoComments.internal_static_NextInfo8_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return YTVideoComments.internal_static_NextInfo8_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NextInfo8.class, Builder.class);
    }

    // Construct using icu.freedomintrovert.YTSendCommAntiFraud.grpcApi.NextInfo8.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      unkMsg49399797_ = null;
      if (unkMsg49399797Builder_ != null) {
        unkMsg49399797Builder_.dispose();
        unkMsg49399797Builder_ = null;
      }
      unkMsg50195462_ = null;
      if (unkMsg50195462Builder_ != null) {
        unkMsg50195462Builder_.dispose();
        unkMsg50195462Builder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return YTVideoComments.internal_static_NextInfo8_descriptor;
    }

    @Override
    public NextInfo8 getDefaultInstanceForType() {
      return NextInfo8.getDefaultInstance();
    }

    @Override
    public NextInfo8 build() {
      NextInfo8 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public NextInfo8 buildPartial() {
      NextInfo8 result = new NextInfo8(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(NextInfo8 result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.unkMsg49399797_ = unkMsg49399797Builder_ == null
            ? unkMsg49399797_
            : unkMsg49399797Builder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.unkMsg50195462_ = unkMsg50195462Builder_ == null
            ? unkMsg50195462_
            : unkMsg50195462Builder_.build();
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof NextInfo8) {
        return mergeFrom((NextInfo8)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(NextInfo8 other) {
      if (other == NextInfo8.getDefaultInstance()) return this;
      if (other.hasUnkMsg49399797()) {
        mergeUnkMsg49399797(other.getUnkMsg49399797());
      }
      if (other.hasUnkMsg50195462()) {
        mergeUnkMsg50195462(other.getUnkMsg50195462());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 395198378: {
              input.readMessage(
                  getUnkMsg49399797FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 395198378
            case 401563698: {
              input.readMessage(
                  getUnkMsg50195462FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 401563698
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private UnkMsg49399797 unkMsg49399797_;
    private com.google.protobuf.SingleFieldBuilderV3<
        UnkMsg49399797, UnkMsg49399797.Builder, UnkMsg49399797OrBuilder> unkMsg49399797Builder_;
    /**
     * <code>.UnkMsg49399797 unkMsg49399797 = 49399797;</code>
     * @return Whether the unkMsg49399797 field is set.
     */
    public boolean hasUnkMsg49399797() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.UnkMsg49399797 unkMsg49399797 = 49399797;</code>
     * @return The unkMsg49399797.
     */
    public UnkMsg49399797 getUnkMsg49399797() {
      if (unkMsg49399797Builder_ == null) {
        return unkMsg49399797_ == null ? UnkMsg49399797.getDefaultInstance() : unkMsg49399797_;
      } else {
        return unkMsg49399797Builder_.getMessage();
      }
    }
    /**
     * <code>.UnkMsg49399797 unkMsg49399797 = 49399797;</code>
     */
    public Builder setUnkMsg49399797(UnkMsg49399797 value) {
      if (unkMsg49399797Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unkMsg49399797_ = value;
      } else {
        unkMsg49399797Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.UnkMsg49399797 unkMsg49399797 = 49399797;</code>
     */
    public Builder setUnkMsg49399797(
        UnkMsg49399797.Builder builderForValue) {
      if (unkMsg49399797Builder_ == null) {
        unkMsg49399797_ = builderForValue.build();
      } else {
        unkMsg49399797Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.UnkMsg49399797 unkMsg49399797 = 49399797;</code>
     */
    public Builder mergeUnkMsg49399797(UnkMsg49399797 value) {
      if (unkMsg49399797Builder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          unkMsg49399797_ != null &&
          unkMsg49399797_ != UnkMsg49399797.getDefaultInstance()) {
          getUnkMsg49399797Builder().mergeFrom(value);
        } else {
          unkMsg49399797_ = value;
        }
      } else {
        unkMsg49399797Builder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.UnkMsg49399797 unkMsg49399797 = 49399797;</code>
     */
    public Builder clearUnkMsg49399797() {
      bitField0_ = (bitField0_ & ~0x00000001);
      unkMsg49399797_ = null;
      if (unkMsg49399797Builder_ != null) {
        unkMsg49399797Builder_.dispose();
        unkMsg49399797Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.UnkMsg49399797 unkMsg49399797 = 49399797;</code>
     */
    public UnkMsg49399797.Builder getUnkMsg49399797Builder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getUnkMsg49399797FieldBuilder().getBuilder();
    }
    /**
     * <code>.UnkMsg49399797 unkMsg49399797 = 49399797;</code>
     */
    public UnkMsg49399797OrBuilder getUnkMsg49399797OrBuilder() {
      if (unkMsg49399797Builder_ != null) {
        return unkMsg49399797Builder_.getMessageOrBuilder();
      } else {
        return unkMsg49399797_ == null ?
            UnkMsg49399797.getDefaultInstance() : unkMsg49399797_;
      }
    }
    /**
     * <code>.UnkMsg49399797 unkMsg49399797 = 49399797;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        UnkMsg49399797, UnkMsg49399797.Builder, UnkMsg49399797OrBuilder>
        getUnkMsg49399797FieldBuilder() {
      if (unkMsg49399797Builder_ == null) {
        unkMsg49399797Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            UnkMsg49399797, UnkMsg49399797.Builder, UnkMsg49399797OrBuilder>(
                getUnkMsg49399797(),
                getParentForChildren(),
                isClean());
        unkMsg49399797_ = null;
      }
      return unkMsg49399797Builder_;
    }

    private UnkMsg50195462 unkMsg50195462_;
    private com.google.protobuf.SingleFieldBuilderV3<
        UnkMsg50195462, UnkMsg50195462.Builder, UnkMsg50195462OrBuilder> unkMsg50195462Builder_;
    /**
     * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
     * @return Whether the unkMsg50195462 field is set.
     */
    public boolean hasUnkMsg50195462() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
     * @return The unkMsg50195462.
     */
    public UnkMsg50195462 getUnkMsg50195462() {
      if (unkMsg50195462Builder_ == null) {
        return unkMsg50195462_ == null ? UnkMsg50195462.getDefaultInstance() : unkMsg50195462_;
      } else {
        return unkMsg50195462Builder_.getMessage();
      }
    }
    /**
     * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
     */
    public Builder setUnkMsg50195462(UnkMsg50195462 value) {
      if (unkMsg50195462Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unkMsg50195462_ = value;
      } else {
        unkMsg50195462Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
     */
    public Builder setUnkMsg50195462(
        UnkMsg50195462.Builder builderForValue) {
      if (unkMsg50195462Builder_ == null) {
        unkMsg50195462_ = builderForValue.build();
      } else {
        unkMsg50195462Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
     */
    public Builder mergeUnkMsg50195462(UnkMsg50195462 value) {
      if (unkMsg50195462Builder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          unkMsg50195462_ != null &&
          unkMsg50195462_ != UnkMsg50195462.getDefaultInstance()) {
          getUnkMsg50195462Builder().mergeFrom(value);
        } else {
          unkMsg50195462_ = value;
        }
      } else {
        unkMsg50195462Builder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
     */
    public Builder clearUnkMsg50195462() {
      bitField0_ = (bitField0_ & ~0x00000002);
      unkMsg50195462_ = null;
      if (unkMsg50195462Builder_ != null) {
        unkMsg50195462Builder_.dispose();
        unkMsg50195462Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
     */
    public UnkMsg50195462.Builder getUnkMsg50195462Builder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getUnkMsg50195462FieldBuilder().getBuilder();
    }
    /**
     * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
     */
    public UnkMsg50195462OrBuilder getUnkMsg50195462OrBuilder() {
      if (unkMsg50195462Builder_ != null) {
        return unkMsg50195462Builder_.getMessageOrBuilder();
      } else {
        return unkMsg50195462_ == null ?
            UnkMsg50195462.getDefaultInstance() : unkMsg50195462_;
      }
    }
    /**
     * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        UnkMsg50195462, UnkMsg50195462.Builder, UnkMsg50195462OrBuilder>
        getUnkMsg50195462FieldBuilder() {
      if (unkMsg50195462Builder_ == null) {
        unkMsg50195462Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            UnkMsg50195462, UnkMsg50195462.Builder, UnkMsg50195462OrBuilder>(
                getUnkMsg50195462(),
                getParentForChildren(),
                isClean());
        unkMsg50195462_ = null;
      }
      return unkMsg50195462Builder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:NextInfo8)
  }

  // @@protoc_insertion_point(class_scope:NextInfo8)
  private static final NextInfo8 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new NextInfo8();
  }

  public static NextInfo8 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NextInfo8>
      PARSER = new com.google.protobuf.AbstractParser<NextInfo8>() {
    @Override
    public NextInfo8 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NextInfo8> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<NextInfo8> getParserForType() {
    return PARSER;
  }

  @Override
  public NextInfo8 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

