// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendComment.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

/**
 * Protobuf type {@code RunAttestationCommand}
 */
public final class RunAttestationCommand extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RunAttestationCommand)
    RunAttestationCommandOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RunAttestationCommand.newBuilder() to construct.
  private RunAttestationCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RunAttestationCommand() {
    ids_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new RunAttestationCommand();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CreatComment.internal_static_RunAttestationCommand_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CreatComment.internal_static_RunAttestationCommand_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RunAttestationCommand.class, Builder.class);
  }

  public static final int IDS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<Ids> ids_;
  /**
   * <code>repeated .Ids ids = 1;</code>
   */
  @Override
  public java.util.List<Ids> getIdsList() {
    return ids_;
  }
  /**
   * <code>repeated .Ids ids = 1;</code>
   */
  @Override
  public java.util.List<? extends IdsOrBuilder>
      getIdsOrBuilderList() {
    return ids_;
  }
  /**
   * <code>repeated .Ids ids = 1;</code>
   */
  @Override
  public int getIdsCount() {
    return ids_.size();
  }
  /**
   * <code>repeated .Ids ids = 1;</code>
   */
  @Override
  public Ids getIds(int index) {
    return ids_.get(index);
  }
  /**
   * <code>repeated .Ids ids = 1;</code>
   */
  @Override
  public IdsOrBuilder getIdsOrBuilder(
      int index) {
    return ids_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < ids_.size(); i++) {
      output.writeMessage(1, ids_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < ids_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, ids_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RunAttestationCommand)) {
      return super.equals(obj);
    }
    RunAttestationCommand other = (RunAttestationCommand) obj;

    if (!getIdsList()
        .equals(other.getIdsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getIdsCount() > 0) {
      hash = (37 * hash) + IDS_FIELD_NUMBER;
      hash = (53 * hash) + getIdsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RunAttestationCommand parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RunAttestationCommand parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RunAttestationCommand parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RunAttestationCommand parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RunAttestationCommand parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RunAttestationCommand parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RunAttestationCommand parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RunAttestationCommand parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static RunAttestationCommand parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static RunAttestationCommand parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RunAttestationCommand parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RunAttestationCommand parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RunAttestationCommand prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RunAttestationCommand}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RunAttestationCommand)
      RunAttestationCommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CreatComment.internal_static_RunAttestationCommand_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CreatComment.internal_static_RunAttestationCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RunAttestationCommand.class, Builder.class);
    }

    // Construct using icu.freedomintrovert.YTSendCommAntiFraud.grpcApi.RunAttestationCommand.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (idsBuilder_ == null) {
        ids_ = java.util.Collections.emptyList();
      } else {
        ids_ = null;
        idsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CreatComment.internal_static_RunAttestationCommand_descriptor;
    }

    @Override
    public RunAttestationCommand getDefaultInstanceForType() {
      return RunAttestationCommand.getDefaultInstance();
    }

    @Override
    public RunAttestationCommand build() {
      RunAttestationCommand result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public RunAttestationCommand buildPartial() {
      RunAttestationCommand result = new RunAttestationCommand(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(RunAttestationCommand result) {
      if (idsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          ids_ = java.util.Collections.unmodifiableList(ids_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ids_ = ids_;
      } else {
        result.ids_ = idsBuilder_.build();
      }
    }

    private void buildPartial0(RunAttestationCommand result) {
      int from_bitField0_ = bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RunAttestationCommand) {
        return mergeFrom((RunAttestationCommand)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RunAttestationCommand other) {
      if (other == RunAttestationCommand.getDefaultInstance()) return this;
      if (idsBuilder_ == null) {
        if (!other.ids_.isEmpty()) {
          if (ids_.isEmpty()) {
            ids_ = other.ids_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIdsIsMutable();
            ids_.addAll(other.ids_);
          }
          onChanged();
        }
      } else {
        if (!other.ids_.isEmpty()) {
          if (idsBuilder_.isEmpty()) {
            idsBuilder_.dispose();
            idsBuilder_ = null;
            ids_ = other.ids_;
            bitField0_ = (bitField0_ & ~0x00000001);
            idsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getIdsFieldBuilder() : null;
          } else {
            idsBuilder_.addAllMessages(other.ids_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Ids m =
                  input.readMessage(
                      Ids.parser(),
                      extensionRegistry);
              if (idsBuilder_ == null) {
                ensureIdsIsMutable();
                ids_.add(m);
              } else {
                idsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<Ids> ids_ =
      java.util.Collections.emptyList();
    private void ensureIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        ids_ = new java.util.ArrayList<Ids>(ids_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Ids, Ids.Builder, IdsOrBuilder> idsBuilder_;

    /**
     * <code>repeated .Ids ids = 1;</code>
     */
    public java.util.List<Ids> getIdsList() {
      if (idsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ids_);
      } else {
        return idsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Ids ids = 1;</code>
     */
    public int getIdsCount() {
      if (idsBuilder_ == null) {
        return ids_.size();
      } else {
        return idsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Ids ids = 1;</code>
     */
    public Ids getIds(int index) {
      if (idsBuilder_ == null) {
        return ids_.get(index);
      } else {
        return idsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Ids ids = 1;</code>
     */
    public Builder setIds(
        int index, Ids value) {
      if (idsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIdsIsMutable();
        ids_.set(index, value);
        onChanged();
      } else {
        idsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Ids ids = 1;</code>
     */
    public Builder setIds(
        int index, Ids.Builder builderForValue) {
      if (idsBuilder_ == null) {
        ensureIdsIsMutable();
        ids_.set(index, builderForValue.build());
        onChanged();
      } else {
        idsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Ids ids = 1;</code>
     */
    public Builder addIds(Ids value) {
      if (idsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIdsIsMutable();
        ids_.add(value);
        onChanged();
      } else {
        idsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Ids ids = 1;</code>
     */
    public Builder addIds(
        int index, Ids value) {
      if (idsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIdsIsMutable();
        ids_.add(index, value);
        onChanged();
      } else {
        idsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Ids ids = 1;</code>
     */
    public Builder addIds(
        Ids.Builder builderForValue) {
      if (idsBuilder_ == null) {
        ensureIdsIsMutable();
        ids_.add(builderForValue.build());
        onChanged();
      } else {
        idsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Ids ids = 1;</code>
     */
    public Builder addIds(
        int index, Ids.Builder builderForValue) {
      if (idsBuilder_ == null) {
        ensureIdsIsMutable();
        ids_.add(index, builderForValue.build());
        onChanged();
      } else {
        idsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Ids ids = 1;</code>
     */
    public Builder addAllIds(
        Iterable<? extends Ids> values) {
      if (idsBuilder_ == null) {
        ensureIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ids_);
        onChanged();
      } else {
        idsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Ids ids = 1;</code>
     */
    public Builder clearIds() {
      if (idsBuilder_ == null) {
        ids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        idsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Ids ids = 1;</code>
     */
    public Builder removeIds(int index) {
      if (idsBuilder_ == null) {
        ensureIdsIsMutable();
        ids_.remove(index);
        onChanged();
      } else {
        idsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Ids ids = 1;</code>
     */
    public Ids.Builder getIdsBuilder(
        int index) {
      return getIdsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Ids ids = 1;</code>
     */
    public IdsOrBuilder getIdsOrBuilder(
        int index) {
      if (idsBuilder_ == null) {
        return ids_.get(index);  } else {
        return idsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Ids ids = 1;</code>
     */
    public java.util.List<? extends IdsOrBuilder>
         getIdsOrBuilderList() {
      if (idsBuilder_ != null) {
        return idsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ids_);
      }
    }
    /**
     * <code>repeated .Ids ids = 1;</code>
     */
    public Ids.Builder addIdsBuilder() {
      return getIdsFieldBuilder().addBuilder(
          Ids.getDefaultInstance());
    }
    /**
     * <code>repeated .Ids ids = 1;</code>
     */
    public Ids.Builder addIdsBuilder(
        int index) {
      return getIdsFieldBuilder().addBuilder(
          index, Ids.getDefaultInstance());
    }
    /**
     * <code>repeated .Ids ids = 1;</code>
     */
    public java.util.List<Ids.Builder>
         getIdsBuilderList() {
      return getIdsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Ids, Ids.Builder, IdsOrBuilder>
        getIdsFieldBuilder() {
      if (idsBuilder_ == null) {
        idsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Ids, Ids.Builder, IdsOrBuilder>(
                ids_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        ids_ = null;
      }
      return idsBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RunAttestationCommand)
  }

  // @@protoc_insertion_point(class_scope:RunAttestationCommand)
  private static final RunAttestationCommand DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RunAttestationCommand();
  }

  public static RunAttestationCommand getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RunAttestationCommand>
      PARSER = new com.google.protobuf.AbstractParser<RunAttestationCommand>() {
    @Override
    public RunAttestationCommand parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RunAttestationCommand> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<RunAttestationCommand> getParserForType() {
    return PARSER;
  }

  @Override
  public RunAttestationCommand getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

