// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendComment.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

public interface RunAttestationCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RunAttestationCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Ids ids = 1;</code>
   */
  java.util.List<Ids>
      getIdsList();
  /**
   * <code>repeated .Ids ids = 1;</code>
   */
  Ids getIds(int index);
  /**
   * <code>repeated .Ids ids = 1;</code>
   */
  int getIdsCount();
  /**
   * <code>repeated .Ids ids = 1;</code>
   */
  java.util.List<? extends IdsOrBuilder>
      getIdsOrBuilderList();
  /**
   * <code>repeated .Ids ids = 1;</code>
   */
  IdsOrBuilder getIdsOrBuilder(
      int index);
}
