// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoComments.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

public interface UNK3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:UNK3)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Comment comment = 40;</code>
   * @return Whether the comment field is set.
   */
  boolean hasComment();
  /**
   * <code>.Comment comment = 40;</code>
   * @return The comment.
   */
  Comment getComment();
  /**
   * <code>.Comment comment = 40;</code>
   */
  CommentOrBuilder getCommentOrBuilder();
}
