// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoComments.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

/**
 * Protobuf type {@code VideoCommentRequest}
 */
public final class VideoCommentRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:VideoCommentRequest)
    VideoCommentRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VideoCommentRequest.newBuilder() to construct.
  private VideoCommentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VideoCommentRequest() {
    continuation_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new VideoCommentRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return YTVideoComments.internal_static_VideoCommentRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return YTVideoComments.internal_static_VideoCommentRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            VideoCommentRequest.class, Builder.class);
  }

  public static final int CONTEXT_FIELD_NUMBER = 1;
  private Context context_;
  /**
   * <code>.Context context = 1;</code>
   * @return Whether the context field is set.
   */
  @Override
  public boolean hasContext() {
    return context_ != null;
  }
  /**
   * <code>.Context context = 1;</code>
   * @return The context.
   */
  @Override
  public Context getContext() {
    return context_ == null ? Context.getDefaultInstance() : context_;
  }
  /**
   * <code>.Context context = 1;</code>
   */
  @Override
  public ContextOrBuilder getContextOrBuilder() {
    return context_ == null ? Context.getDefaultInstance() : context_;
  }

  public static final int CONTINUATION_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile Object continuation_ = "";
  /**
   * <code>string continuation = 8;</code>
   * @return The continuation.
   */
  @Override
  public String getContinuation() {
    Object ref = continuation_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      continuation_ = s;
      return s;
    }
  }
  /**
   * <code>string continuation = 8;</code>
   * @return The bytes for continuation.
   */
  @Override
  public com.google.protobuf.ByteString
      getContinuationBytes() {
    Object ref = continuation_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      continuation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (context_ != null) {
      output.writeMessage(1, getContext());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(continuation_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, continuation_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (context_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getContext());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(continuation_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, continuation_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof VideoCommentRequest)) {
      return super.equals(obj);
    }
    VideoCommentRequest other = (VideoCommentRequest) obj;

    if (hasContext() != other.hasContext()) return false;
    if (hasContext()) {
      if (!getContext()
          .equals(other.getContext())) return false;
    }
    if (!getContinuation()
        .equals(other.getContinuation())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasContext()) {
      hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getContext().hashCode();
    }
    hash = (37 * hash) + CONTINUATION_FIELD_NUMBER;
    hash = (53 * hash) + getContinuation().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static VideoCommentRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VideoCommentRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VideoCommentRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VideoCommentRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VideoCommentRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VideoCommentRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VideoCommentRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static VideoCommentRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static VideoCommentRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static VideoCommentRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static VideoCommentRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static VideoCommentRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(VideoCommentRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code VideoCommentRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:VideoCommentRequest)
      VideoCommentRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return YTVideoComments.internal_static_VideoCommentRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return YTVideoComments.internal_static_VideoCommentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VideoCommentRequest.class, Builder.class);
    }

    // Construct using icu.freedomintrovert.YTSendCommAntiFraud.grpcApi.VideoCommentRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      context_ = null;
      if (contextBuilder_ != null) {
        contextBuilder_.dispose();
        contextBuilder_ = null;
      }
      continuation_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return YTVideoComments.internal_static_VideoCommentRequest_descriptor;
    }

    @Override
    public VideoCommentRequest getDefaultInstanceForType() {
      return VideoCommentRequest.getDefaultInstance();
    }

    @Override
    public VideoCommentRequest build() {
      VideoCommentRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public VideoCommentRequest buildPartial() {
      VideoCommentRequest result = new VideoCommentRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(VideoCommentRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.context_ = contextBuilder_ == null
            ? context_
            : contextBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.continuation_ = continuation_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof VideoCommentRequest) {
        return mergeFrom((VideoCommentRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(VideoCommentRequest other) {
      if (other == VideoCommentRequest.getDefaultInstance()) return this;
      if (other.hasContext()) {
        mergeContext(other.getContext());
      }
      if (!other.getContinuation().isEmpty()) {
        continuation_ = other.continuation_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getContextFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 66: {
              continuation_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Context context_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Context, Context.Builder, ContextOrBuilder> contextBuilder_;
    /**
     * <code>.Context context = 1;</code>
     * @return Whether the context field is set.
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Context context = 1;</code>
     * @return The context.
     */
    public Context getContext() {
      if (contextBuilder_ == null) {
        return context_ == null ? Context.getDefaultInstance() : context_;
      } else {
        return contextBuilder_.getMessage();
      }
    }
    /**
     * <code>.Context context = 1;</code>
     */
    public Builder setContext(Context value) {
      if (contextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        context_ = value;
      } else {
        contextBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Context context = 1;</code>
     */
    public Builder setContext(
        Context.Builder builderForValue) {
      if (contextBuilder_ == null) {
        context_ = builderForValue.build();
      } else {
        contextBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Context context = 1;</code>
     */
    public Builder mergeContext(Context value) {
      if (contextBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          context_ != null &&
          context_ != Context.getDefaultInstance()) {
          getContextBuilder().mergeFrom(value);
        } else {
          context_ = value;
        }
      } else {
        contextBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Context context = 1;</code>
     */
    public Builder clearContext() {
      bitField0_ = (bitField0_ & ~0x00000001);
      context_ = null;
      if (contextBuilder_ != null) {
        contextBuilder_.dispose();
        contextBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Context context = 1;</code>
     */
    public Context.Builder getContextBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getContextFieldBuilder().getBuilder();
    }
    /**
     * <code>.Context context = 1;</code>
     */
    public ContextOrBuilder getContextOrBuilder() {
      if (contextBuilder_ != null) {
        return contextBuilder_.getMessageOrBuilder();
      } else {
        return context_ == null ?
            Context.getDefaultInstance() : context_;
      }
    }
    /**
     * <code>.Context context = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Context, Context.Builder, ContextOrBuilder>
        getContextFieldBuilder() {
      if (contextBuilder_ == null) {
        contextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Context, Context.Builder, ContextOrBuilder>(
                getContext(),
                getParentForChildren(),
                isClean());
        context_ = null;
      }
      return contextBuilder_;
    }

    private Object continuation_ = "";
    /**
     * <code>string continuation = 8;</code>
     * @return The continuation.
     */
    public String getContinuation() {
      Object ref = continuation_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        continuation_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string continuation = 8;</code>
     * @return The bytes for continuation.
     */
    public com.google.protobuf.ByteString
        getContinuationBytes() {
      Object ref = continuation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        continuation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string continuation = 8;</code>
     * @param value The continuation to set.
     * @return This builder for chaining.
     */
    public Builder setContinuation(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      continuation_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string continuation = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearContinuation() {
      continuation_ = getDefaultInstance().getContinuation();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string continuation = 8;</code>
     * @param value The bytes for continuation to set.
     * @return This builder for chaining.
     */
    public Builder setContinuationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      continuation_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:VideoCommentRequest)
  }

  // @@protoc_insertion_point(class_scope:VideoCommentRequest)
  private static final VideoCommentRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new VideoCommentRequest();
  }

  public static VideoCommentRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VideoCommentRequest>
      PARSER = new com.google.protobuf.AbstractParser<VideoCommentRequest>() {
    @Override
    public VideoCommentRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VideoCommentRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<VideoCommentRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public VideoCommentRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

