// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoComments.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

/**
 * Protobuf type {@code VideoCommentResponse}
 */
public final class VideoCommentResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:VideoCommentResponse)
    VideoCommentResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VideoCommentResponse.newBuilder() to construct.
  private VideoCommentResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VideoCommentResponse() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new VideoCommentResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return YTVideoComments.internal_static_VideoCommentResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return YTVideoComments.internal_static_VideoCommentResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            VideoCommentResponse.class, Builder.class);
  }

  public static final int CONTINUATIONITEMSACTION_FIELD_NUMBER = 777;
  private ContinuationItemsAction777 continuationItemsAction_;
  /**
   * <code>.ContinuationItemsAction777 ContinuationItemsAction = 777;</code>
   * @return Whether the continuationItemsAction field is set.
   */
  @Override
  public boolean hasContinuationItemsAction() {
    return continuationItemsAction_ != null;
  }
  /**
   * <code>.ContinuationItemsAction777 ContinuationItemsAction = 777;</code>
   * @return The continuationItemsAction.
   */
  @Override
  public ContinuationItemsAction777 getContinuationItemsAction() {
    return continuationItemsAction_ == null ? ContinuationItemsAction777.getDefaultInstance() : continuationItemsAction_;
  }
  /**
   * <code>.ContinuationItemsAction777 ContinuationItemsAction = 777;</code>
   */
  @Override
  public ContinuationItemsAction777OrBuilder getContinuationItemsActionOrBuilder() {
    return continuationItemsAction_ == null ? ContinuationItemsAction777.getDefaultInstance() : continuationItemsAction_;
  }

  public static final int NEXTINFO8_FIELD_NUMBER = 8;
  private NextInfo8 nextInfo8_;
  /**
   * <code>.NextInfo8 nextInfo8 = 8;</code>
   * @return Whether the nextInfo8 field is set.
   */
  @Override
  public boolean hasNextInfo8() {
    return nextInfo8_ != null;
  }
  /**
   * <code>.NextInfo8 nextInfo8 = 8;</code>
   * @return The nextInfo8.
   */
  @Override
  public NextInfo8 getNextInfo8() {
    return nextInfo8_ == null ? NextInfo8.getDefaultInstance() : nextInfo8_;
  }
  /**
   * <code>.NextInfo8 nextInfo8 = 8;</code>
   */
  @Override
  public NextInfo8OrBuilder getNextInfo8OrBuilder() {
    return nextInfo8_ == null ? NextInfo8.getDefaultInstance() : nextInfo8_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (nextInfo8_ != null) {
      output.writeMessage(8, getNextInfo8());
    }
    if (continuationItemsAction_ != null) {
      output.writeMessage(777, getContinuationItemsAction());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (nextInfo8_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getNextInfo8());
    }
    if (continuationItemsAction_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(777, getContinuationItemsAction());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof VideoCommentResponse)) {
      return super.equals(obj);
    }
    VideoCommentResponse other = (VideoCommentResponse) obj;

    if (hasContinuationItemsAction() != other.hasContinuationItemsAction()) return false;
    if (hasContinuationItemsAction()) {
      if (!getContinuationItemsAction()
          .equals(other.getContinuationItemsAction())) return false;
    }
    if (hasNextInfo8() != other.hasNextInfo8()) return false;
    if (hasNextInfo8()) {
      if (!getNextInfo8()
          .equals(other.getNextInfo8())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasContinuationItemsAction()) {
      hash = (37 * hash) + CONTINUATIONITEMSACTION_FIELD_NUMBER;
      hash = (53 * hash) + getContinuationItemsAction().hashCode();
    }
    if (hasNextInfo8()) {
      hash = (37 * hash) + NEXTINFO8_FIELD_NUMBER;
      hash = (53 * hash) + getNextInfo8().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static VideoCommentResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VideoCommentResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VideoCommentResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VideoCommentResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VideoCommentResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VideoCommentResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VideoCommentResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static VideoCommentResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static VideoCommentResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static VideoCommentResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static VideoCommentResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static VideoCommentResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(VideoCommentResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code VideoCommentResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:VideoCommentResponse)
      VideoCommentResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return YTVideoComments.internal_static_VideoCommentResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return YTVideoComments.internal_static_VideoCommentResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VideoCommentResponse.class, Builder.class);
    }

    // Construct using icu.freedomintrovert.YTSendCommAntiFraud.grpcApi.VideoCommentResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      continuationItemsAction_ = null;
      if (continuationItemsActionBuilder_ != null) {
        continuationItemsActionBuilder_.dispose();
        continuationItemsActionBuilder_ = null;
      }
      nextInfo8_ = null;
      if (nextInfo8Builder_ != null) {
        nextInfo8Builder_.dispose();
        nextInfo8Builder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return YTVideoComments.internal_static_VideoCommentResponse_descriptor;
    }

    @Override
    public VideoCommentResponse getDefaultInstanceForType() {
      return VideoCommentResponse.getDefaultInstance();
    }

    @Override
    public VideoCommentResponse build() {
      VideoCommentResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public VideoCommentResponse buildPartial() {
      VideoCommentResponse result = new VideoCommentResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(VideoCommentResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.continuationItemsAction_ = continuationItemsActionBuilder_ == null
            ? continuationItemsAction_
            : continuationItemsActionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.nextInfo8_ = nextInfo8Builder_ == null
            ? nextInfo8_
            : nextInfo8Builder_.build();
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof VideoCommentResponse) {
        return mergeFrom((VideoCommentResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(VideoCommentResponse other) {
      if (other == VideoCommentResponse.getDefaultInstance()) return this;
      if (other.hasContinuationItemsAction()) {
        mergeContinuationItemsAction(other.getContinuationItemsAction());
      }
      if (other.hasNextInfo8()) {
        mergeNextInfo8(other.getNextInfo8());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 66: {
              input.readMessage(
                  getNextInfo8FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 66
            case 6218: {
              input.readMessage(
                  getContinuationItemsActionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 6218
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private ContinuationItemsAction777 continuationItemsAction_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ContinuationItemsAction777, ContinuationItemsAction777.Builder, ContinuationItemsAction777OrBuilder> continuationItemsActionBuilder_;
    /**
     * <code>.ContinuationItemsAction777 ContinuationItemsAction = 777;</code>
     * @return Whether the continuationItemsAction field is set.
     */
    public boolean hasContinuationItemsAction() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.ContinuationItemsAction777 ContinuationItemsAction = 777;</code>
     * @return The continuationItemsAction.
     */
    public ContinuationItemsAction777 getContinuationItemsAction() {
      if (continuationItemsActionBuilder_ == null) {
        return continuationItemsAction_ == null ? ContinuationItemsAction777.getDefaultInstance() : continuationItemsAction_;
      } else {
        return continuationItemsActionBuilder_.getMessage();
      }
    }
    /**
     * <code>.ContinuationItemsAction777 ContinuationItemsAction = 777;</code>
     */
    public Builder setContinuationItemsAction(ContinuationItemsAction777 value) {
      if (continuationItemsActionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        continuationItemsAction_ = value;
      } else {
        continuationItemsActionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ContinuationItemsAction777 ContinuationItemsAction = 777;</code>
     */
    public Builder setContinuationItemsAction(
        ContinuationItemsAction777.Builder builderForValue) {
      if (continuationItemsActionBuilder_ == null) {
        continuationItemsAction_ = builderForValue.build();
      } else {
        continuationItemsActionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ContinuationItemsAction777 ContinuationItemsAction = 777;</code>
     */
    public Builder mergeContinuationItemsAction(ContinuationItemsAction777 value) {
      if (continuationItemsActionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          continuationItemsAction_ != null &&
          continuationItemsAction_ != ContinuationItemsAction777.getDefaultInstance()) {
          getContinuationItemsActionBuilder().mergeFrom(value);
        } else {
          continuationItemsAction_ = value;
        }
      } else {
        continuationItemsActionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ContinuationItemsAction777 ContinuationItemsAction = 777;</code>
     */
    public Builder clearContinuationItemsAction() {
      bitField0_ = (bitField0_ & ~0x00000001);
      continuationItemsAction_ = null;
      if (continuationItemsActionBuilder_ != null) {
        continuationItemsActionBuilder_.dispose();
        continuationItemsActionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.ContinuationItemsAction777 ContinuationItemsAction = 777;</code>
     */
    public ContinuationItemsAction777.Builder getContinuationItemsActionBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getContinuationItemsActionFieldBuilder().getBuilder();
    }
    /**
     * <code>.ContinuationItemsAction777 ContinuationItemsAction = 777;</code>
     */
    public ContinuationItemsAction777OrBuilder getContinuationItemsActionOrBuilder() {
      if (continuationItemsActionBuilder_ != null) {
        return continuationItemsActionBuilder_.getMessageOrBuilder();
      } else {
        return continuationItemsAction_ == null ?
            ContinuationItemsAction777.getDefaultInstance() : continuationItemsAction_;
      }
    }
    /**
     * <code>.ContinuationItemsAction777 ContinuationItemsAction = 777;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ContinuationItemsAction777, ContinuationItemsAction777.Builder, ContinuationItemsAction777OrBuilder>
        getContinuationItemsActionFieldBuilder() {
      if (continuationItemsActionBuilder_ == null) {
        continuationItemsActionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ContinuationItemsAction777, ContinuationItemsAction777.Builder, ContinuationItemsAction777OrBuilder>(
                getContinuationItemsAction(),
                getParentForChildren(),
                isClean());
        continuationItemsAction_ = null;
      }
      return continuationItemsActionBuilder_;
    }

    private NextInfo8 nextInfo8_;
    private com.google.protobuf.SingleFieldBuilderV3<
        NextInfo8, NextInfo8.Builder, NextInfo8OrBuilder> nextInfo8Builder_;
    /**
     * <code>.NextInfo8 nextInfo8 = 8;</code>
     * @return Whether the nextInfo8 field is set.
     */
    public boolean hasNextInfo8() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.NextInfo8 nextInfo8 = 8;</code>
     * @return The nextInfo8.
     */
    public NextInfo8 getNextInfo8() {
      if (nextInfo8Builder_ == null) {
        return nextInfo8_ == null ? NextInfo8.getDefaultInstance() : nextInfo8_;
      } else {
        return nextInfo8Builder_.getMessage();
      }
    }
    /**
     * <code>.NextInfo8 nextInfo8 = 8;</code>
     */
    public Builder setNextInfo8(NextInfo8 value) {
      if (nextInfo8Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nextInfo8_ = value;
      } else {
        nextInfo8Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.NextInfo8 nextInfo8 = 8;</code>
     */
    public Builder setNextInfo8(
        NextInfo8.Builder builderForValue) {
      if (nextInfo8Builder_ == null) {
        nextInfo8_ = builderForValue.build();
      } else {
        nextInfo8Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.NextInfo8 nextInfo8 = 8;</code>
     */
    public Builder mergeNextInfo8(NextInfo8 value) {
      if (nextInfo8Builder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          nextInfo8_ != null &&
          nextInfo8_ != NextInfo8.getDefaultInstance()) {
          getNextInfo8Builder().mergeFrom(value);
        } else {
          nextInfo8_ = value;
        }
      } else {
        nextInfo8Builder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.NextInfo8 nextInfo8 = 8;</code>
     */
    public Builder clearNextInfo8() {
      bitField0_ = (bitField0_ & ~0x00000002);
      nextInfo8_ = null;
      if (nextInfo8Builder_ != null) {
        nextInfo8Builder_.dispose();
        nextInfo8Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.NextInfo8 nextInfo8 = 8;</code>
     */
    public NextInfo8.Builder getNextInfo8Builder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getNextInfo8FieldBuilder().getBuilder();
    }
    /**
     * <code>.NextInfo8 nextInfo8 = 8;</code>
     */
    public NextInfo8OrBuilder getNextInfo8OrBuilder() {
      if (nextInfo8Builder_ != null) {
        return nextInfo8Builder_.getMessageOrBuilder();
      } else {
        return nextInfo8_ == null ?
            NextInfo8.getDefaultInstance() : nextInfo8_;
      }
    }
    /**
     * <code>.NextInfo8 nextInfo8 = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        NextInfo8, NextInfo8.Builder, NextInfo8OrBuilder>
        getNextInfo8FieldBuilder() {
      if (nextInfo8Builder_ == null) {
        nextInfo8Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            NextInfo8, NextInfo8.Builder, NextInfo8OrBuilder>(
                getNextInfo8(),
                getParentForChildren(),
                isClean());
        nextInfo8_ = null;
      }
      return nextInfo8Builder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:VideoCommentResponse)
  }

  // @@protoc_insertion_point(class_scope:VideoCommentResponse)
  private static final VideoCommentResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new VideoCommentResponse();
  }

  public static VideoCommentResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VideoCommentResponse>
      PARSER = new com.google.protobuf.AbstractParser<VideoCommentResponse>() {
    @Override
    public VideoCommentResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VideoCommentResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<VideoCommentResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public VideoCommentResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

