// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContinuationCommand.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi.nestedIntoBase64;

public interface CommentSectionInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CommentSectionInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.CommentSectionInfo.Config config = 4;</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <code>.CommentSectionInfo.Config config = 4;</code>
   * @return The config.
   */
  CommentSectionInfo.Config getConfig();
  /**
   * <code>.CommentSectionInfo.Config config = 4;</code>
   */
  CommentSectionInfo.ConfigOrBuilder getConfigOrBuilder();

  /**
   * <pre>
   *通常为"comments-section"
   * </pre>
   *
   * <code>string comments_sectionMy = 8;</code>
   * @return The commentsSectionMy.
   */
  String getCommentsSectionMy();
  /**
   * <pre>
   *通常为"comments-section"
   * </pre>
   *
   * <code>string comments_sectionMy = 8;</code>
   * @return The bytes for commentsSectionMy.
   */
  com.google.protobuf.ByteString
      getCommentsSectionMyBytes();
}
