// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContinuationCommand.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi.nestedIntoBase64;

public interface ContinuationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Continuation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.VideoIdMsg videoIdMsg = 2;</code>
   * @return Whether the videoIdMsg field is set.
   */
  boolean hasVideoIdMsg();
  /**
   * <code>.VideoIdMsg videoIdMsg = 2;</code>
   * @return The videoIdMsg.
   */
  VideoIdMsg getVideoIdMsg();
  /**
   * <code>.VideoIdMsg videoIdMsg = 2;</code>
   */
  VideoIdMsgOrBuilder getVideoIdMsgOrBuilder();

  /**
   * <pre>
   *通常为6,未知属性
   * </pre>
   *
   * <code>int32 unknownInt_3 = 3;</code>
   * @return The unknownInt3.
   */
  int getUnknownInt3();

  /**
   * <code>.CommentSectionInfo commentSectionInfo = 6;</code>
   * @return Whether the commentSectionInfo field is set.
   */
  boolean hasCommentSectionInfo();
  /**
   * <code>.CommentSectionInfo commentSectionInfo = 6;</code>
   * @return The commentSectionInfo.
   */
  CommentSectionInfo getCommentSectionInfo();
  /**
   * <code>.CommentSectionInfo commentSectionInfo = 6;</code>
   */
  CommentSectionInfoOrBuilder getCommentSectionInfoOrBuilder();
}
