// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContinuationCommand.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi.nestedIntoBase64;

/**
 * Protobuf enum {@code SortBy}
 */
public enum SortBy
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>hot = 0;</code>
   */
  hot(0),
  /**
   * <code>latest = 1;</code>
   */
  latest(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>hot = 0;</code>
   */
  public static final int hot_VALUE = 0;
  /**
   * <code>latest = 1;</code>
   */
  public static final int latest_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static SortBy valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SortBy forNumber(int value) {
    switch (value) {
      case 0: return hot;
      case 1: return latest;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SortBy>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SortBy> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SortBy>() {
          public SortBy findValueByNumber(int number) {
            return SortBy.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ContinuationCommand.getDescriptor().getEnumTypes().get(0);
  }

  private static final SortBy[] VALUES = values();

  public static SortBy valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SortBy(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:SortBy)
}

