// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoComments.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

public interface ContinuationItemsAction777OrBuilder extends
    // @@protoc_insertion_point(interface_extends:ContinuationItemsAction777)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ContinuationItems continuationItems = 1;</code>
   * @return Whether the continuationItems field is set.
   */
  boolean hasContinuationItems();
  /**
   * <code>.ContinuationItems continuationItems = 1;</code>
   * @return The continuationItems.
   */
  ContinuationItems getContinuationItems();
  /**
   * <code>.ContinuationItems continuationItems = 1;</code>
   */
  ContinuationItemsOrBuilder getContinuationItemsOrBuilder();
}
