// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoComments.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

/**
 * Protobuf type {@code ContinuationItems}
 */
public final class ContinuationItems extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ContinuationItems)
    ContinuationItemsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ContinuationItems.newBuilder() to construct.
  private ContinuationItems(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ContinuationItems() {
    continuationItem_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ContinuationItems();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return YTVideoComments.internal_static_ContinuationItems_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return YTVideoComments.internal_static_ContinuationItems_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ContinuationItems.class, Builder.class);
  }

  public static final int CONTINUATIONITEM_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<ContinuationItem> continuationItem_;
  /**
   * <code>repeated .ContinuationItem continuationItem = 1;</code>
   */
  @Override
  public java.util.List<ContinuationItem> getContinuationItemList() {
    return continuationItem_;
  }
  /**
   * <code>repeated .ContinuationItem continuationItem = 1;</code>
   */
  @Override
  public java.util.List<? extends ContinuationItemOrBuilder>
      getContinuationItemOrBuilderList() {
    return continuationItem_;
  }
  /**
   * <code>repeated .ContinuationItem continuationItem = 1;</code>
   */
  @Override
  public int getContinuationItemCount() {
    return continuationItem_.size();
  }
  /**
   * <code>repeated .ContinuationItem continuationItem = 1;</code>
   */
  @Override
  public ContinuationItem getContinuationItem(int index) {
    return continuationItem_.get(index);
  }
  /**
   * <code>repeated .ContinuationItem continuationItem = 1;</code>
   */
  @Override
  public ContinuationItemOrBuilder getContinuationItemOrBuilder(
      int index) {
    return continuationItem_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < continuationItem_.size(); i++) {
      output.writeMessage(1, continuationItem_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < continuationItem_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, continuationItem_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ContinuationItems)) {
      return super.equals(obj);
    }
    ContinuationItems other = (ContinuationItems) obj;

    if (!getContinuationItemList()
        .equals(other.getContinuationItemList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getContinuationItemCount() > 0) {
      hash = (37 * hash) + CONTINUATIONITEM_FIELD_NUMBER;
      hash = (53 * hash) + getContinuationItemList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ContinuationItems parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ContinuationItems parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ContinuationItems parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ContinuationItems parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ContinuationItems parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ContinuationItems parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ContinuationItems parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ContinuationItems parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ContinuationItems parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ContinuationItems parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ContinuationItems parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ContinuationItems parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ContinuationItems prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ContinuationItems}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ContinuationItems)
      ContinuationItemsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return YTVideoComments.internal_static_ContinuationItems_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return YTVideoComments.internal_static_ContinuationItems_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ContinuationItems.class, Builder.class);
    }

    // Construct using icu.freedomintrovert.YTSendCommAntiFraud.grpcApi.ContinuationItems.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (continuationItemBuilder_ == null) {
        continuationItem_ = java.util.Collections.emptyList();
      } else {
        continuationItem_ = null;
        continuationItemBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return YTVideoComments.internal_static_ContinuationItems_descriptor;
    }

    @Override
    public ContinuationItems getDefaultInstanceForType() {
      return ContinuationItems.getDefaultInstance();
    }

    @Override
    public ContinuationItems build() {
      ContinuationItems result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ContinuationItems buildPartial() {
      ContinuationItems result = new ContinuationItems(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ContinuationItems result) {
      if (continuationItemBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          continuationItem_ = java.util.Collections.unmodifiableList(continuationItem_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.continuationItem_ = continuationItem_;
      } else {
        result.continuationItem_ = continuationItemBuilder_.build();
      }
    }

    private void buildPartial0(ContinuationItems result) {
      int from_bitField0_ = bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ContinuationItems) {
        return mergeFrom((ContinuationItems)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ContinuationItems other) {
      if (other == ContinuationItems.getDefaultInstance()) return this;
      if (continuationItemBuilder_ == null) {
        if (!other.continuationItem_.isEmpty()) {
          if (continuationItem_.isEmpty()) {
            continuationItem_ = other.continuationItem_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureContinuationItemIsMutable();
            continuationItem_.addAll(other.continuationItem_);
          }
          onChanged();
        }
      } else {
        if (!other.continuationItem_.isEmpty()) {
          if (continuationItemBuilder_.isEmpty()) {
            continuationItemBuilder_.dispose();
            continuationItemBuilder_ = null;
            continuationItem_ = other.continuationItem_;
            bitField0_ = (bitField0_ & ~0x00000001);
            continuationItemBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getContinuationItemFieldBuilder() : null;
          } else {
            continuationItemBuilder_.addAllMessages(other.continuationItem_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ContinuationItem m =
                  input.readMessage(
                      ContinuationItem.parser(),
                      extensionRegistry);
              if (continuationItemBuilder_ == null) {
                ensureContinuationItemIsMutable();
                continuationItem_.add(m);
              } else {
                continuationItemBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<ContinuationItem> continuationItem_ =
      java.util.Collections.emptyList();
    private void ensureContinuationItemIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        continuationItem_ = new java.util.ArrayList<ContinuationItem>(continuationItem_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ContinuationItem, ContinuationItem.Builder, ContinuationItemOrBuilder> continuationItemBuilder_;

    /**
     * <code>repeated .ContinuationItem continuationItem = 1;</code>
     */
    public java.util.List<ContinuationItem> getContinuationItemList() {
      if (continuationItemBuilder_ == null) {
        return java.util.Collections.unmodifiableList(continuationItem_);
      } else {
        return continuationItemBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ContinuationItem continuationItem = 1;</code>
     */
    public int getContinuationItemCount() {
      if (continuationItemBuilder_ == null) {
        return continuationItem_.size();
      } else {
        return continuationItemBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ContinuationItem continuationItem = 1;</code>
     */
    public ContinuationItem getContinuationItem(int index) {
      if (continuationItemBuilder_ == null) {
        return continuationItem_.get(index);
      } else {
        return continuationItemBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ContinuationItem continuationItem = 1;</code>
     */
    public Builder setContinuationItem(
        int index, ContinuationItem value) {
      if (continuationItemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContinuationItemIsMutable();
        continuationItem_.set(index, value);
        onChanged();
      } else {
        continuationItemBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ContinuationItem continuationItem = 1;</code>
     */
    public Builder setContinuationItem(
        int index, ContinuationItem.Builder builderForValue) {
      if (continuationItemBuilder_ == null) {
        ensureContinuationItemIsMutable();
        continuationItem_.set(index, builderForValue.build());
        onChanged();
      } else {
        continuationItemBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ContinuationItem continuationItem = 1;</code>
     */
    public Builder addContinuationItem(ContinuationItem value) {
      if (continuationItemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContinuationItemIsMutable();
        continuationItem_.add(value);
        onChanged();
      } else {
        continuationItemBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ContinuationItem continuationItem = 1;</code>
     */
    public Builder addContinuationItem(
        int index, ContinuationItem value) {
      if (continuationItemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContinuationItemIsMutable();
        continuationItem_.add(index, value);
        onChanged();
      } else {
        continuationItemBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ContinuationItem continuationItem = 1;</code>
     */
    public Builder addContinuationItem(
        ContinuationItem.Builder builderForValue) {
      if (continuationItemBuilder_ == null) {
        ensureContinuationItemIsMutable();
        continuationItem_.add(builderForValue.build());
        onChanged();
      } else {
        continuationItemBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ContinuationItem continuationItem = 1;</code>
     */
    public Builder addContinuationItem(
        int index, ContinuationItem.Builder builderForValue) {
      if (continuationItemBuilder_ == null) {
        ensureContinuationItemIsMutable();
        continuationItem_.add(index, builderForValue.build());
        onChanged();
      } else {
        continuationItemBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ContinuationItem continuationItem = 1;</code>
     */
    public Builder addAllContinuationItem(
        Iterable<? extends ContinuationItem> values) {
      if (continuationItemBuilder_ == null) {
        ensureContinuationItemIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, continuationItem_);
        onChanged();
      } else {
        continuationItemBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ContinuationItem continuationItem = 1;</code>
     */
    public Builder clearContinuationItem() {
      if (continuationItemBuilder_ == null) {
        continuationItem_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        continuationItemBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ContinuationItem continuationItem = 1;</code>
     */
    public Builder removeContinuationItem(int index) {
      if (continuationItemBuilder_ == null) {
        ensureContinuationItemIsMutable();
        continuationItem_.remove(index);
        onChanged();
      } else {
        continuationItemBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ContinuationItem continuationItem = 1;</code>
     */
    public ContinuationItem.Builder getContinuationItemBuilder(
        int index) {
      return getContinuationItemFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ContinuationItem continuationItem = 1;</code>
     */
    public ContinuationItemOrBuilder getContinuationItemOrBuilder(
        int index) {
      if (continuationItemBuilder_ == null) {
        return continuationItem_.get(index);  } else {
        return continuationItemBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ContinuationItem continuationItem = 1;</code>
     */
    public java.util.List<? extends ContinuationItemOrBuilder>
         getContinuationItemOrBuilderList() {
      if (continuationItemBuilder_ != null) {
        return continuationItemBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(continuationItem_);
      }
    }
    /**
     * <code>repeated .ContinuationItem continuationItem = 1;</code>
     */
    public ContinuationItem.Builder addContinuationItemBuilder() {
      return getContinuationItemFieldBuilder().addBuilder(
          ContinuationItem.getDefaultInstance());
    }
    /**
     * <code>repeated .ContinuationItem continuationItem = 1;</code>
     */
    public ContinuationItem.Builder addContinuationItemBuilder(
        int index) {
      return getContinuationItemFieldBuilder().addBuilder(
          index, ContinuationItem.getDefaultInstance());
    }
    /**
     * <code>repeated .ContinuationItem continuationItem = 1;</code>
     */
    public java.util.List<ContinuationItem.Builder>
         getContinuationItemBuilderList() {
      return getContinuationItemFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ContinuationItem, ContinuationItem.Builder, ContinuationItemOrBuilder>
        getContinuationItemFieldBuilder() {
      if (continuationItemBuilder_ == null) {
        continuationItemBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ContinuationItem, ContinuationItem.Builder, ContinuationItemOrBuilder>(
                continuationItem_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        continuationItem_ = null;
      }
      return continuationItemBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ContinuationItems)
  }

  // @@protoc_insertion_point(class_scope:ContinuationItems)
  private static final ContinuationItems DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ContinuationItems();
  }

  public static ContinuationItems getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ContinuationItems>
      PARSER = new com.google.protobuf.AbstractParser<ContinuationItems>() {
    @Override
    public ContinuationItems parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ContinuationItems> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ContinuationItems> getParserForType() {
    return PARSER;
  }

  @Override
  public ContinuationItems getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

