// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendComment.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

public interface Context1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:Context1)
    com.google.protobuf.MessageOrBuilder {
}
