// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendComment.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

/**
 * Protobuf type {@code Ids}
 */
public final class Ids extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Ids)
    IdsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Ids.newBuilder() to construct.
  private Ids(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Ids() {
    commentId_ = "";
    encryptedVideoId_ = "";
    externalChannelId_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Ids();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CreatComment.internal_static_Ids_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CreatComment.internal_static_Ids_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Ids.class, Builder.class);
  }

  public static final int COMMENTID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object commentId_ = "";
  /**
   * <code>string commentId = 3;</code>
   * @return The commentId.
   */
  @Override
  public String getCommentId() {
    Object ref = commentId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      commentId_ = s;
      return s;
    }
  }
  /**
   * <code>string commentId = 3;</code>
   * @return The bytes for commentId.
   */
  @Override
  public com.google.protobuf.ByteString
      getCommentIdBytes() {
    Object ref = commentId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      commentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENCRYPTEDVIDEOID_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile Object encryptedVideoId_ = "";
  /**
   * <code>string encryptedVideoId = 8;</code>
   * @return The encryptedVideoId.
   */
  @Override
  public String getEncryptedVideoId() {
    Object ref = encryptedVideoId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      encryptedVideoId_ = s;
      return s;
    }
  }
  /**
   * <code>string encryptedVideoId = 8;</code>
   * @return The bytes for encryptedVideoId.
   */
  @Override
  public com.google.protobuf.ByteString
      getEncryptedVideoIdBytes() {
    Object ref = encryptedVideoId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      encryptedVideoId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTERNALCHANNELID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object externalChannelId_ = "";
  /**
   * <code>string externalChannelId = 2;</code>
   * @return The externalChannelId.
   */
  @Override
  public String getExternalChannelId() {
    Object ref = externalChannelId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      externalChannelId_ = s;
      return s;
    }
  }
  /**
   * <code>string externalChannelId = 2;</code>
   * @return The bytes for externalChannelId.
   */
  @Override
  public com.google.protobuf.ByteString
      getExternalChannelIdBytes() {
    Object ref = externalChannelId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      externalChannelId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(externalChannelId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, externalChannelId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commentId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, commentId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(encryptedVideoId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, encryptedVideoId_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(externalChannelId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, externalChannelId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commentId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, commentId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(encryptedVideoId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, encryptedVideoId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Ids)) {
      return super.equals(obj);
    }
    Ids other = (Ids) obj;

    if (!getCommentId()
        .equals(other.getCommentId())) return false;
    if (!getEncryptedVideoId()
        .equals(other.getEncryptedVideoId())) return false;
    if (!getExternalChannelId()
        .equals(other.getExternalChannelId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMENTID_FIELD_NUMBER;
    hash = (53 * hash) + getCommentId().hashCode();
    hash = (37 * hash) + ENCRYPTEDVIDEOID_FIELD_NUMBER;
    hash = (53 * hash) + getEncryptedVideoId().hashCode();
    hash = (37 * hash) + EXTERNALCHANNELID_FIELD_NUMBER;
    hash = (53 * hash) + getExternalChannelId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Ids parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Ids parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Ids parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Ids parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Ids parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Ids parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Ids parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Ids parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Ids parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Ids parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Ids parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Ids parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Ids prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Ids}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Ids)
      IdsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CreatComment.internal_static_Ids_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CreatComment.internal_static_Ids_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Ids.class, Builder.class);
    }

    // Construct using icu.freedomintrovert.YTSendCommAntiFraud.grpcApi.Ids.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      commentId_ = "";
      encryptedVideoId_ = "";
      externalChannelId_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CreatComment.internal_static_Ids_descriptor;
    }

    @Override
    public Ids getDefaultInstanceForType() {
      return Ids.getDefaultInstance();
    }

    @Override
    public Ids build() {
      Ids result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Ids buildPartial() {
      Ids result = new Ids(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(Ids result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.commentId_ = commentId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.encryptedVideoId_ = encryptedVideoId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.externalChannelId_ = externalChannelId_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Ids) {
        return mergeFrom((Ids)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Ids other) {
      if (other == Ids.getDefaultInstance()) return this;
      if (!other.getCommentId().isEmpty()) {
        commentId_ = other.commentId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getEncryptedVideoId().isEmpty()) {
        encryptedVideoId_ = other.encryptedVideoId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getExternalChannelId().isEmpty()) {
        externalChannelId_ = other.externalChannelId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              externalChannelId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 18
            case 26: {
              commentId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 26
            case 66: {
              encryptedVideoId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object commentId_ = "";
    /**
     * <code>string commentId = 3;</code>
     * @return The commentId.
     */
    public String getCommentId() {
      Object ref = commentId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        commentId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string commentId = 3;</code>
     * @return The bytes for commentId.
     */
    public com.google.protobuf.ByteString
        getCommentIdBytes() {
      Object ref = commentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        commentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string commentId = 3;</code>
     * @param value The commentId to set.
     * @return This builder for chaining.
     */
    public Builder setCommentId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      commentId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string commentId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommentId() {
      commentId_ = getDefaultInstance().getCommentId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string commentId = 3;</code>
     * @param value The bytes for commentId to set.
     * @return This builder for chaining.
     */
    public Builder setCommentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      commentId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object encryptedVideoId_ = "";
    /**
     * <code>string encryptedVideoId = 8;</code>
     * @return The encryptedVideoId.
     */
    public String getEncryptedVideoId() {
      Object ref = encryptedVideoId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        encryptedVideoId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string encryptedVideoId = 8;</code>
     * @return The bytes for encryptedVideoId.
     */
    public com.google.protobuf.ByteString
        getEncryptedVideoIdBytes() {
      Object ref = encryptedVideoId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        encryptedVideoId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string encryptedVideoId = 8;</code>
     * @param value The encryptedVideoId to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptedVideoId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      encryptedVideoId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string encryptedVideoId = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryptedVideoId() {
      encryptedVideoId_ = getDefaultInstance().getEncryptedVideoId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string encryptedVideoId = 8;</code>
     * @param value The bytes for encryptedVideoId to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptedVideoIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      encryptedVideoId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private Object externalChannelId_ = "";
    /**
     * <code>string externalChannelId = 2;</code>
     * @return The externalChannelId.
     */
    public String getExternalChannelId() {
      Object ref = externalChannelId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        externalChannelId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string externalChannelId = 2;</code>
     * @return The bytes for externalChannelId.
     */
    public com.google.protobuf.ByteString
        getExternalChannelIdBytes() {
      Object ref = externalChannelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        externalChannelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string externalChannelId = 2;</code>
     * @param value The externalChannelId to set.
     * @return This builder for chaining.
     */
    public Builder setExternalChannelId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      externalChannelId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string externalChannelId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExternalChannelId() {
      externalChannelId_ = getDefaultInstance().getExternalChannelId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string externalChannelId = 2;</code>
     * @param value The bytes for externalChannelId to set.
     * @return This builder for chaining.
     */
    public Builder setExternalChannelIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      externalChannelId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Ids)
  }

  // @@protoc_insertion_point(class_scope:Ids)
  private static final Ids DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Ids();
  }

  public static Ids getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Ids>
      PARSER = new com.google.protobuf.AbstractParser<Ids>() {
    @Override
    public Ids parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Ids> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Ids> getParserForType() {
    return PARSER;
  }

  @Override
  public Ids getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

