// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoComments.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

/**
 * Protobuf type {@code UnkMsg50195462}
 */
public final class UnkMsg50195462 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UnkMsg50195462)
    UnkMsg50195462OrBuilder {
private static final long serialVersionUID = 0L;
  // Use UnkMsg50195462.newBuilder() to construct.
  private UnkMsg50195462(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UnkMsg50195462() {
    unkMsg2_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new UnkMsg50195462();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return YTVideoComments.internal_static_UnkMsg50195462_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return YTVideoComments.internal_static_UnkMsg50195462_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            UnkMsg50195462.class, Builder.class);
  }

  public interface UnkMsg2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:UnkMsg50195462.UnkMsg2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.UnkMsg50195462.UnkMsg2.UnkMsg52047593 unkMsg52047593 = 52047593;</code>
     * @return Whether the unkMsg52047593 field is set.
     */
    boolean hasUnkMsg52047593();
    /**
     * <code>.UnkMsg50195462.UnkMsg2.UnkMsg52047593 unkMsg52047593 = 52047593;</code>
     * @return The unkMsg52047593.
     */
    UnkMsg2.UnkMsg52047593 getUnkMsg52047593();
    /**
     * <code>.UnkMsg50195462.UnkMsg2.UnkMsg52047593 unkMsg52047593 = 52047593;</code>
     */
    UnkMsg2.UnkMsg52047593OrBuilder getUnkMsg52047593OrBuilder();
  }
  /**
   * Protobuf type {@code UnkMsg50195462.UnkMsg2}
   */
  public static final class UnkMsg2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UnkMsg50195462.UnkMsg2)
      UnkMsg2OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UnkMsg2.newBuilder() to construct.
    private UnkMsg2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UnkMsg2() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new UnkMsg2();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return YTVideoComments.internal_static_UnkMsg50195462_UnkMsg2_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return YTVideoComments.internal_static_UnkMsg50195462_UnkMsg2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UnkMsg2.class, Builder.class);
    }

    public interface UnkMsg52047593OrBuilder extends
        // @@protoc_insertion_point(interface_extends:UnkMsg50195462.UnkMsg2.UnkMsg52047593)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string continuation = 1;</code>
       * @return The continuation.
       */
      String getContinuation();
      /**
       * <code>string continuation = 1;</code>
       * @return The bytes for continuation.
       */
      com.google.protobuf.ByteString
          getContinuationBytes();
    }
    /**
     * Protobuf type {@code UnkMsg50195462.UnkMsg2.UnkMsg52047593}
     */
    public static final class UnkMsg52047593 extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:UnkMsg50195462.UnkMsg2.UnkMsg52047593)
        UnkMsg52047593OrBuilder {
    private static final long serialVersionUID = 0L;
      // Use UnkMsg52047593.newBuilder() to construct.
      private UnkMsg52047593(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private UnkMsg52047593() {
        continuation_ = "";
      }

      @Override
      @SuppressWarnings({"unused"})
      protected Object newInstance(
          UnusedPrivateParameter unused) {
        return new UnkMsg52047593();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return YTVideoComments.internal_static_UnkMsg50195462_UnkMsg2_UnkMsg52047593_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return YTVideoComments.internal_static_UnkMsg50195462_UnkMsg2_UnkMsg52047593_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UnkMsg52047593.class, Builder.class);
      }

      public static final int CONTINUATION_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile Object continuation_ = "";
      /**
       * <code>string continuation = 1;</code>
       * @return The continuation.
       */
      @Override
      public String getContinuation() {
        Object ref = continuation_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          continuation_ = s;
          return s;
        }
      }
      /**
       * <code>string continuation = 1;</code>
       * @return The bytes for continuation.
       */
      @Override
      public com.google.protobuf.ByteString
          getContinuationBytes() {
        Object ref = continuation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          continuation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(continuation_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, continuation_);
        }
        getUnknownFields().writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(continuation_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, continuation_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof UnkMsg52047593)) {
          return super.equals(obj);
        }
        UnkMsg52047593 other = (UnkMsg52047593) obj;

        if (!getContinuation()
            .equals(other.getContinuation())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CONTINUATION_FIELD_NUMBER;
        hash = (53 * hash) + getContinuation().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static UnkMsg52047593 parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static UnkMsg52047593 parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static UnkMsg52047593 parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static UnkMsg52047593 parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static UnkMsg52047593 parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static UnkMsg52047593 parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static UnkMsg52047593 parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static UnkMsg52047593 parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static UnkMsg52047593 parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static UnkMsg52047593 parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static UnkMsg52047593 parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static UnkMsg52047593 parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(UnkMsg52047593 prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code UnkMsg50195462.UnkMsg2.UnkMsg52047593}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:UnkMsg50195462.UnkMsg2.UnkMsg52047593)
          UnkMsg52047593OrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return YTVideoComments.internal_static_UnkMsg50195462_UnkMsg2_UnkMsg52047593_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return YTVideoComments.internal_static_UnkMsg50195462_UnkMsg2_UnkMsg52047593_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  UnkMsg52047593.class, Builder.class);
        }

        // Construct using icu.freedomintrovert.YTSendCommAntiFraud.grpcApi.UnkMsg50195462.UnkMsg2.UnkMsg52047593.newBuilder()
        private Builder() {

        }

        private Builder(
            BuilderParent parent) {
          super(parent);

        }
        @Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          continuation_ = "";
          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return YTVideoComments.internal_static_UnkMsg50195462_UnkMsg2_UnkMsg52047593_descriptor;
        }

        @Override
        public UnkMsg52047593 getDefaultInstanceForType() {
          return UnkMsg52047593.getDefaultInstance();
        }

        @Override
        public UnkMsg52047593 build() {
          UnkMsg52047593 result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public UnkMsg52047593 buildPartial() {
          UnkMsg52047593 result = new UnkMsg52047593(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(UnkMsg52047593 result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.continuation_ = continuation_;
          }
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof UnkMsg52047593) {
            return mergeFrom((UnkMsg52047593)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(UnkMsg52047593 other) {
          if (other == UnkMsg52047593.getDefaultInstance()) return this;
          if (!other.getContinuation().isEmpty()) {
            continuation_ = other.continuation_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  continuation_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private Object continuation_ = "";
        /**
         * <code>string continuation = 1;</code>
         * @return The continuation.
         */
        public String getContinuation() {
          Object ref = continuation_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            continuation_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string continuation = 1;</code>
         * @return The bytes for continuation.
         */
        public com.google.protobuf.ByteString
            getContinuationBytes() {
          Object ref = continuation_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            continuation_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string continuation = 1;</code>
         * @param value The continuation to set.
         * @return This builder for chaining.
         */
        public Builder setContinuation(
            String value) {
          if (value == null) { throw new NullPointerException(); }
          continuation_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>string continuation = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearContinuation() {
          continuation_ = getDefaultInstance().getContinuation();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>string continuation = 1;</code>
         * @param value The bytes for continuation to set.
         * @return This builder for chaining.
         */
        public Builder setContinuationBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          continuation_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:UnkMsg50195462.UnkMsg2.UnkMsg52047593)
      }

      // @@protoc_insertion_point(class_scope:UnkMsg50195462.UnkMsg2.UnkMsg52047593)
      private static final UnkMsg52047593 DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new UnkMsg52047593();
      }

      public static UnkMsg52047593 getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<UnkMsg52047593>
          PARSER = new com.google.protobuf.AbstractParser<UnkMsg52047593>() {
        @Override
        public UnkMsg52047593 parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<UnkMsg52047593> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<UnkMsg52047593> getParserForType() {
        return PARSER;
      }

      @Override
      public UnkMsg52047593 getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int UNKMSG52047593_FIELD_NUMBER = 52047593;
    private UnkMsg52047593 unkMsg52047593_;
    /**
     * <code>.UnkMsg50195462.UnkMsg2.UnkMsg52047593 unkMsg52047593 = 52047593;</code>
     * @return Whether the unkMsg52047593 field is set.
     */
    @Override
    public boolean hasUnkMsg52047593() {
      return unkMsg52047593_ != null;
    }
    /**
     * <code>.UnkMsg50195462.UnkMsg2.UnkMsg52047593 unkMsg52047593 = 52047593;</code>
     * @return The unkMsg52047593.
     */
    @Override
    public UnkMsg52047593 getUnkMsg52047593() {
      return unkMsg52047593_ == null ? UnkMsg52047593.getDefaultInstance() : unkMsg52047593_;
    }
    /**
     * <code>.UnkMsg50195462.UnkMsg2.UnkMsg52047593 unkMsg52047593 = 52047593;</code>
     */
    @Override
    public UnkMsg52047593OrBuilder getUnkMsg52047593OrBuilder() {
      return unkMsg52047593_ == null ? UnkMsg52047593.getDefaultInstance() : unkMsg52047593_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (unkMsg52047593_ != null) {
        output.writeMessage(52047593, getUnkMsg52047593());
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (unkMsg52047593_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(52047593, getUnkMsg52047593());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UnkMsg2)) {
        return super.equals(obj);
      }
      UnkMsg2 other = (UnkMsg2) obj;

      if (hasUnkMsg52047593() != other.hasUnkMsg52047593()) return false;
      if (hasUnkMsg52047593()) {
        if (!getUnkMsg52047593()
            .equals(other.getUnkMsg52047593())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUnkMsg52047593()) {
        hash = (37 * hash) + UNKMSG52047593_FIELD_NUMBER;
        hash = (53 * hash) + getUnkMsg52047593().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UnkMsg2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UnkMsg2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UnkMsg2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UnkMsg2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UnkMsg2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UnkMsg2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UnkMsg2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UnkMsg2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UnkMsg2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UnkMsg2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UnkMsg2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UnkMsg2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UnkMsg2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UnkMsg50195462.UnkMsg2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UnkMsg50195462.UnkMsg2)
        UnkMsg2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return YTVideoComments.internal_static_UnkMsg50195462_UnkMsg2_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return YTVideoComments.internal_static_UnkMsg50195462_UnkMsg2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UnkMsg2.class, Builder.class);
      }

      // Construct using icu.freedomintrovert.YTSendCommAntiFraud.grpcApi.UnkMsg50195462.UnkMsg2.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        unkMsg52047593_ = null;
        if (unkMsg52047593Builder_ != null) {
          unkMsg52047593Builder_.dispose();
          unkMsg52047593Builder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return YTVideoComments.internal_static_UnkMsg50195462_UnkMsg2_descriptor;
      }

      @Override
      public UnkMsg2 getDefaultInstanceForType() {
        return UnkMsg2.getDefaultInstance();
      }

      @Override
      public UnkMsg2 build() {
        UnkMsg2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UnkMsg2 buildPartial() {
        UnkMsg2 result = new UnkMsg2(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(UnkMsg2 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.unkMsg52047593_ = unkMsg52047593Builder_ == null
              ? unkMsg52047593_
              : unkMsg52047593Builder_.build();
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UnkMsg2) {
          return mergeFrom((UnkMsg2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UnkMsg2 other) {
        if (other == UnkMsg2.getDefaultInstance()) return this;
        if (other.hasUnkMsg52047593()) {
          mergeUnkMsg52047593(other.getUnkMsg52047593());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 416380746: {
                input.readMessage(
                    getUnkMsg52047593FieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 416380746
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private UnkMsg52047593 unkMsg52047593_;
      private com.google.protobuf.SingleFieldBuilderV3<
          UnkMsg52047593, UnkMsg52047593.Builder, UnkMsg52047593OrBuilder> unkMsg52047593Builder_;
      /**
       * <code>.UnkMsg50195462.UnkMsg2.UnkMsg52047593 unkMsg52047593 = 52047593;</code>
       * @return Whether the unkMsg52047593 field is set.
       */
      public boolean hasUnkMsg52047593() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.UnkMsg50195462.UnkMsg2.UnkMsg52047593 unkMsg52047593 = 52047593;</code>
       * @return The unkMsg52047593.
       */
      public UnkMsg52047593 getUnkMsg52047593() {
        if (unkMsg52047593Builder_ == null) {
          return unkMsg52047593_ == null ? UnkMsg52047593.getDefaultInstance() : unkMsg52047593_;
        } else {
          return unkMsg52047593Builder_.getMessage();
        }
      }
      /**
       * <code>.UnkMsg50195462.UnkMsg2.UnkMsg52047593 unkMsg52047593 = 52047593;</code>
       */
      public Builder setUnkMsg52047593(UnkMsg52047593 value) {
        if (unkMsg52047593Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          unkMsg52047593_ = value;
        } else {
          unkMsg52047593Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.UnkMsg50195462.UnkMsg2.UnkMsg52047593 unkMsg52047593 = 52047593;</code>
       */
      public Builder setUnkMsg52047593(
          UnkMsg52047593.Builder builderForValue) {
        if (unkMsg52047593Builder_ == null) {
          unkMsg52047593_ = builderForValue.build();
        } else {
          unkMsg52047593Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.UnkMsg50195462.UnkMsg2.UnkMsg52047593 unkMsg52047593 = 52047593;</code>
       */
      public Builder mergeUnkMsg52047593(UnkMsg52047593 value) {
        if (unkMsg52047593Builder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            unkMsg52047593_ != null &&
            unkMsg52047593_ != UnkMsg52047593.getDefaultInstance()) {
            getUnkMsg52047593Builder().mergeFrom(value);
          } else {
            unkMsg52047593_ = value;
          }
        } else {
          unkMsg52047593Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.UnkMsg50195462.UnkMsg2.UnkMsg52047593 unkMsg52047593 = 52047593;</code>
       */
      public Builder clearUnkMsg52047593() {
        bitField0_ = (bitField0_ & ~0x00000001);
        unkMsg52047593_ = null;
        if (unkMsg52047593Builder_ != null) {
          unkMsg52047593Builder_.dispose();
          unkMsg52047593Builder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.UnkMsg50195462.UnkMsg2.UnkMsg52047593 unkMsg52047593 = 52047593;</code>
       */
      public UnkMsg52047593.Builder getUnkMsg52047593Builder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getUnkMsg52047593FieldBuilder().getBuilder();
      }
      /**
       * <code>.UnkMsg50195462.UnkMsg2.UnkMsg52047593 unkMsg52047593 = 52047593;</code>
       */
      public UnkMsg52047593OrBuilder getUnkMsg52047593OrBuilder() {
        if (unkMsg52047593Builder_ != null) {
          return unkMsg52047593Builder_.getMessageOrBuilder();
        } else {
          return unkMsg52047593_ == null ?
              UnkMsg52047593.getDefaultInstance() : unkMsg52047593_;
        }
      }
      /**
       * <code>.UnkMsg50195462.UnkMsg2.UnkMsg52047593 unkMsg52047593 = 52047593;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          UnkMsg52047593, UnkMsg52047593.Builder, UnkMsg52047593OrBuilder>
          getUnkMsg52047593FieldBuilder() {
        if (unkMsg52047593Builder_ == null) {
          unkMsg52047593Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              UnkMsg52047593, UnkMsg52047593.Builder, UnkMsg52047593OrBuilder>(
                  getUnkMsg52047593(),
                  getParentForChildren(),
                  isClean());
          unkMsg52047593_ = null;
        }
        return unkMsg52047593Builder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UnkMsg50195462.UnkMsg2)
    }

    // @@protoc_insertion_point(class_scope:UnkMsg50195462.UnkMsg2)
    private static final UnkMsg2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UnkMsg2();
    }

    public static UnkMsg2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UnkMsg2>
        PARSER = new com.google.protobuf.AbstractParser<UnkMsg2>() {
      @Override
      public UnkMsg2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UnkMsg2> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UnkMsg2> getParserForType() {
      return PARSER;
    }

    @Override
    public UnkMsg2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int UNKMSG2_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<UnkMsg2> unkMsg2_;
  /**
   * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
   */
  @Override
  public java.util.List<UnkMsg2> getUnkMsg2List() {
    return unkMsg2_;
  }
  /**
   * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
   */
  @Override
  public java.util.List<? extends UnkMsg2OrBuilder>
      getUnkMsg2OrBuilderList() {
    return unkMsg2_;
  }
  /**
   * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
   */
  @Override
  public int getUnkMsg2Count() {
    return unkMsg2_.size();
  }
  /**
   * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
   */
  @Override
  public UnkMsg2 getUnkMsg2(int index) {
    return unkMsg2_.get(index);
  }
  /**
   * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
   */
  @Override
  public UnkMsg2OrBuilder getUnkMsg2OrBuilder(
      int index) {
    return unkMsg2_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < unkMsg2_.size(); i++) {
      output.writeMessage(2, unkMsg2_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < unkMsg2_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, unkMsg2_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof UnkMsg50195462)) {
      return super.equals(obj);
    }
    UnkMsg50195462 other = (UnkMsg50195462) obj;

    if (!getUnkMsg2List()
        .equals(other.getUnkMsg2List())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUnkMsg2Count() > 0) {
      hash = (37 * hash) + UNKMSG2_FIELD_NUMBER;
      hash = (53 * hash) + getUnkMsg2List().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static UnkMsg50195462 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UnkMsg50195462 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UnkMsg50195462 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UnkMsg50195462 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UnkMsg50195462 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UnkMsg50195462 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UnkMsg50195462 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UnkMsg50195462 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static UnkMsg50195462 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static UnkMsg50195462 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static UnkMsg50195462 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UnkMsg50195462 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(UnkMsg50195462 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UnkMsg50195462}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UnkMsg50195462)
      UnkMsg50195462OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return YTVideoComments.internal_static_UnkMsg50195462_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return YTVideoComments.internal_static_UnkMsg50195462_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UnkMsg50195462.class, Builder.class);
    }

    // Construct using icu.freedomintrovert.YTSendCommAntiFraud.grpcApi.UnkMsg50195462.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (unkMsg2Builder_ == null) {
        unkMsg2_ = java.util.Collections.emptyList();
      } else {
        unkMsg2_ = null;
        unkMsg2Builder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return YTVideoComments.internal_static_UnkMsg50195462_descriptor;
    }

    @Override
    public UnkMsg50195462 getDefaultInstanceForType() {
      return UnkMsg50195462.getDefaultInstance();
    }

    @Override
    public UnkMsg50195462 build() {
      UnkMsg50195462 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public UnkMsg50195462 buildPartial() {
      UnkMsg50195462 result = new UnkMsg50195462(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(UnkMsg50195462 result) {
      if (unkMsg2Builder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          unkMsg2_ = java.util.Collections.unmodifiableList(unkMsg2_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.unkMsg2_ = unkMsg2_;
      } else {
        result.unkMsg2_ = unkMsg2Builder_.build();
      }
    }

    private void buildPartial0(UnkMsg50195462 result) {
      int from_bitField0_ = bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof UnkMsg50195462) {
        return mergeFrom((UnkMsg50195462)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(UnkMsg50195462 other) {
      if (other == UnkMsg50195462.getDefaultInstance()) return this;
      if (unkMsg2Builder_ == null) {
        if (!other.unkMsg2_.isEmpty()) {
          if (unkMsg2_.isEmpty()) {
            unkMsg2_ = other.unkMsg2_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUnkMsg2IsMutable();
            unkMsg2_.addAll(other.unkMsg2_);
          }
          onChanged();
        }
      } else {
        if (!other.unkMsg2_.isEmpty()) {
          if (unkMsg2Builder_.isEmpty()) {
            unkMsg2Builder_.dispose();
            unkMsg2Builder_ = null;
            unkMsg2_ = other.unkMsg2_;
            bitField0_ = (bitField0_ & ~0x00000001);
            unkMsg2Builder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUnkMsg2FieldBuilder() : null;
          } else {
            unkMsg2Builder_.addAllMessages(other.unkMsg2_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              UnkMsg2 m =
                  input.readMessage(
                      UnkMsg2.parser(),
                      extensionRegistry);
              if (unkMsg2Builder_ == null) {
                ensureUnkMsg2IsMutable();
                unkMsg2_.add(m);
              } else {
                unkMsg2Builder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<UnkMsg2> unkMsg2_ =
      java.util.Collections.emptyList();
    private void ensureUnkMsg2IsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        unkMsg2_ = new java.util.ArrayList<UnkMsg2>(unkMsg2_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        UnkMsg2, UnkMsg2.Builder, UnkMsg2OrBuilder> unkMsg2Builder_;

    /**
     * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
     */
    public java.util.List<UnkMsg2> getUnkMsg2List() {
      if (unkMsg2Builder_ == null) {
        return java.util.Collections.unmodifiableList(unkMsg2_);
      } else {
        return unkMsg2Builder_.getMessageList();
      }
    }
    /**
     * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
     */
    public int getUnkMsg2Count() {
      if (unkMsg2Builder_ == null) {
        return unkMsg2_.size();
      } else {
        return unkMsg2Builder_.getCount();
      }
    }
    /**
     * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
     */
    public UnkMsg2 getUnkMsg2(int index) {
      if (unkMsg2Builder_ == null) {
        return unkMsg2_.get(index);
      } else {
        return unkMsg2Builder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
     */
    public Builder setUnkMsg2(
        int index, UnkMsg2 value) {
      if (unkMsg2Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUnkMsg2IsMutable();
        unkMsg2_.set(index, value);
        onChanged();
      } else {
        unkMsg2Builder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
     */
    public Builder setUnkMsg2(
        int index, UnkMsg2.Builder builderForValue) {
      if (unkMsg2Builder_ == null) {
        ensureUnkMsg2IsMutable();
        unkMsg2_.set(index, builderForValue.build());
        onChanged();
      } else {
        unkMsg2Builder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
     */
    public Builder addUnkMsg2(UnkMsg2 value) {
      if (unkMsg2Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUnkMsg2IsMutable();
        unkMsg2_.add(value);
        onChanged();
      } else {
        unkMsg2Builder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
     */
    public Builder addUnkMsg2(
        int index, UnkMsg2 value) {
      if (unkMsg2Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUnkMsg2IsMutable();
        unkMsg2_.add(index, value);
        onChanged();
      } else {
        unkMsg2Builder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
     */
    public Builder addUnkMsg2(
        UnkMsg2.Builder builderForValue) {
      if (unkMsg2Builder_ == null) {
        ensureUnkMsg2IsMutable();
        unkMsg2_.add(builderForValue.build());
        onChanged();
      } else {
        unkMsg2Builder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
     */
    public Builder addUnkMsg2(
        int index, UnkMsg2.Builder builderForValue) {
      if (unkMsg2Builder_ == null) {
        ensureUnkMsg2IsMutable();
        unkMsg2_.add(index, builderForValue.build());
        onChanged();
      } else {
        unkMsg2Builder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
     */
    public Builder addAllUnkMsg2(
        Iterable<? extends UnkMsg2> values) {
      if (unkMsg2Builder_ == null) {
        ensureUnkMsg2IsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, unkMsg2_);
        onChanged();
      } else {
        unkMsg2Builder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
     */
    public Builder clearUnkMsg2() {
      if (unkMsg2Builder_ == null) {
        unkMsg2_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        unkMsg2Builder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
     */
    public Builder removeUnkMsg2(int index) {
      if (unkMsg2Builder_ == null) {
        ensureUnkMsg2IsMutable();
        unkMsg2_.remove(index);
        onChanged();
      } else {
        unkMsg2Builder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
     */
    public UnkMsg2.Builder getUnkMsg2Builder(
        int index) {
      return getUnkMsg2FieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
     */
    public UnkMsg2OrBuilder getUnkMsg2OrBuilder(
        int index) {
      if (unkMsg2Builder_ == null) {
        return unkMsg2_.get(index);  } else {
        return unkMsg2Builder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
     */
    public java.util.List<? extends UnkMsg2OrBuilder>
         getUnkMsg2OrBuilderList() {
      if (unkMsg2Builder_ != null) {
        return unkMsg2Builder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(unkMsg2_);
      }
    }
    /**
     * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
     */
    public UnkMsg2.Builder addUnkMsg2Builder() {
      return getUnkMsg2FieldBuilder().addBuilder(
          UnkMsg2.getDefaultInstance());
    }
    /**
     * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
     */
    public UnkMsg2.Builder addUnkMsg2Builder(
        int index) {
      return getUnkMsg2FieldBuilder().addBuilder(
          index, UnkMsg2.getDefaultInstance());
    }
    /**
     * <code>repeated .UnkMsg50195462.UnkMsg2 unkMsg2 = 2;</code>
     */
    public java.util.List<UnkMsg2.Builder>
         getUnkMsg2BuilderList() {
      return getUnkMsg2FieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        UnkMsg2, UnkMsg2.Builder, UnkMsg2OrBuilder>
        getUnkMsg2FieldBuilder() {
      if (unkMsg2Builder_ == null) {
        unkMsg2Builder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            UnkMsg2, UnkMsg2.Builder, UnkMsg2OrBuilder>(
                unkMsg2_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        unkMsg2_ = null;
      }
      return unkMsg2Builder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UnkMsg50195462)
  }

  // @@protoc_insertion_point(class_scope:UnkMsg50195462)
  private static final UnkMsg50195462 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new UnkMsg50195462();
  }

  public static UnkMsg50195462 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UnkMsg50195462>
      PARSER = new com.google.protobuf.AbstractParser<UnkMsg50195462>() {
    @Override
    public UnkMsg50195462 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UnkMsg50195462> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<UnkMsg50195462> getParserForType() {
    return PARSER;
  }

  @Override
  public UnkMsg50195462 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

