// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoComments.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

/**
 * Protobuf type {@code UnkMsg49399797}
 */
public final class UnkMsg49399797 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UnkMsg49399797)
    UnkMsg49399797OrBuilder {
private static final long serialVersionUID = 0L;
  // Use UnkMsg49399797.newBuilder() to construct.
  private UnkMsg49399797(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UnkMsg49399797() {
    unkMsg1_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new UnkMsg49399797();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return YTVideoComments.internal_static_UnkMsg49399797_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return YTVideoComments.internal_static_UnkMsg49399797_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            UnkMsg49399797.class, Builder.class);
  }

  public interface UnkMsg49399797_1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:UnkMsg49399797.UnkMsg49399797_1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
     * @return Whether the unkMsg50195462 field is set.
     */
    boolean hasUnkMsg50195462();
    /**
     * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
     * @return The unkMsg50195462.
     */
    UnkMsg50195462 getUnkMsg50195462();
    /**
     * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
     */
    UnkMsg50195462OrBuilder getUnkMsg50195462OrBuilder();
  }
  /**
   * Protobuf type {@code UnkMsg49399797.UnkMsg49399797_1}
   */
  public static final class UnkMsg49399797_1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UnkMsg49399797.UnkMsg49399797_1)
      UnkMsg49399797_1OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UnkMsg49399797_1.newBuilder() to construct.
    private UnkMsg49399797_1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UnkMsg49399797_1() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new UnkMsg49399797_1();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return YTVideoComments.internal_static_UnkMsg49399797_UnkMsg49399797_1_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return YTVideoComments.internal_static_UnkMsg49399797_UnkMsg49399797_1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UnkMsg49399797_1.class, Builder.class);
    }

    public static final int UNKMSG50195462_FIELD_NUMBER = 50195462;
    private UnkMsg50195462 unkMsg50195462_;
    /**
     * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
     * @return Whether the unkMsg50195462 field is set.
     */
    @Override
    public boolean hasUnkMsg50195462() {
      return unkMsg50195462_ != null;
    }
    /**
     * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
     * @return The unkMsg50195462.
     */
    @Override
    public UnkMsg50195462 getUnkMsg50195462() {
      return unkMsg50195462_ == null ? UnkMsg50195462.getDefaultInstance() : unkMsg50195462_;
    }
    /**
     * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
     */
    @Override
    public UnkMsg50195462OrBuilder getUnkMsg50195462OrBuilder() {
      return unkMsg50195462_ == null ? UnkMsg50195462.getDefaultInstance() : unkMsg50195462_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (unkMsg50195462_ != null) {
        output.writeMessage(50195462, getUnkMsg50195462());
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (unkMsg50195462_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(50195462, getUnkMsg50195462());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UnkMsg49399797_1)) {
        return super.equals(obj);
      }
      UnkMsg49399797_1 other = (UnkMsg49399797_1) obj;

      if (hasUnkMsg50195462() != other.hasUnkMsg50195462()) return false;
      if (hasUnkMsg50195462()) {
        if (!getUnkMsg50195462()
            .equals(other.getUnkMsg50195462())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUnkMsg50195462()) {
        hash = (37 * hash) + UNKMSG50195462_FIELD_NUMBER;
        hash = (53 * hash) + getUnkMsg50195462().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UnkMsg49399797_1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UnkMsg49399797_1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UnkMsg49399797_1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UnkMsg49399797_1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UnkMsg49399797_1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UnkMsg49399797_1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UnkMsg49399797_1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UnkMsg49399797_1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UnkMsg49399797_1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UnkMsg49399797_1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UnkMsg49399797_1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UnkMsg49399797_1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UnkMsg49399797_1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UnkMsg49399797.UnkMsg49399797_1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UnkMsg49399797.UnkMsg49399797_1)
        UnkMsg49399797_1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return YTVideoComments.internal_static_UnkMsg49399797_UnkMsg49399797_1_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return YTVideoComments.internal_static_UnkMsg49399797_UnkMsg49399797_1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UnkMsg49399797_1.class, Builder.class);
      }

      // Construct using icu.freedomintrovert.YTSendCommAntiFraud.grpcApi.UnkMsg49399797.UnkMsg49399797_1.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        unkMsg50195462_ = null;
        if (unkMsg50195462Builder_ != null) {
          unkMsg50195462Builder_.dispose();
          unkMsg50195462Builder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return YTVideoComments.internal_static_UnkMsg49399797_UnkMsg49399797_1_descriptor;
      }

      @Override
      public UnkMsg49399797_1 getDefaultInstanceForType() {
        return UnkMsg49399797_1.getDefaultInstance();
      }

      @Override
      public UnkMsg49399797_1 build() {
        UnkMsg49399797_1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UnkMsg49399797_1 buildPartial() {
        UnkMsg49399797_1 result = new UnkMsg49399797_1(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(UnkMsg49399797_1 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.unkMsg50195462_ = unkMsg50195462Builder_ == null
              ? unkMsg50195462_
              : unkMsg50195462Builder_.build();
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UnkMsg49399797_1) {
          return mergeFrom((UnkMsg49399797_1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UnkMsg49399797_1 other) {
        if (other == UnkMsg49399797_1.getDefaultInstance()) return this;
        if (other.hasUnkMsg50195462()) {
          mergeUnkMsg50195462(other.getUnkMsg50195462());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 401563698: {
                input.readMessage(
                    getUnkMsg50195462FieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 401563698
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private UnkMsg50195462 unkMsg50195462_;
      private com.google.protobuf.SingleFieldBuilderV3<
          UnkMsg50195462, UnkMsg50195462.Builder, UnkMsg50195462OrBuilder> unkMsg50195462Builder_;
      /**
       * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
       * @return Whether the unkMsg50195462 field is set.
       */
      public boolean hasUnkMsg50195462() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
       * @return The unkMsg50195462.
       */
      public UnkMsg50195462 getUnkMsg50195462() {
        if (unkMsg50195462Builder_ == null) {
          return unkMsg50195462_ == null ? UnkMsg50195462.getDefaultInstance() : unkMsg50195462_;
        } else {
          return unkMsg50195462Builder_.getMessage();
        }
      }
      /**
       * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
       */
      public Builder setUnkMsg50195462(UnkMsg50195462 value) {
        if (unkMsg50195462Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          unkMsg50195462_ = value;
        } else {
          unkMsg50195462Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
       */
      public Builder setUnkMsg50195462(
          UnkMsg50195462.Builder builderForValue) {
        if (unkMsg50195462Builder_ == null) {
          unkMsg50195462_ = builderForValue.build();
        } else {
          unkMsg50195462Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
       */
      public Builder mergeUnkMsg50195462(UnkMsg50195462 value) {
        if (unkMsg50195462Builder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            unkMsg50195462_ != null &&
            unkMsg50195462_ != UnkMsg50195462.getDefaultInstance()) {
            getUnkMsg50195462Builder().mergeFrom(value);
          } else {
            unkMsg50195462_ = value;
          }
        } else {
          unkMsg50195462Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
       */
      public Builder clearUnkMsg50195462() {
        bitField0_ = (bitField0_ & ~0x00000001);
        unkMsg50195462_ = null;
        if (unkMsg50195462Builder_ != null) {
          unkMsg50195462Builder_.dispose();
          unkMsg50195462Builder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
       */
      public UnkMsg50195462.Builder getUnkMsg50195462Builder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getUnkMsg50195462FieldBuilder().getBuilder();
      }
      /**
       * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
       */
      public UnkMsg50195462OrBuilder getUnkMsg50195462OrBuilder() {
        if (unkMsg50195462Builder_ != null) {
          return unkMsg50195462Builder_.getMessageOrBuilder();
        } else {
          return unkMsg50195462_ == null ?
              UnkMsg50195462.getDefaultInstance() : unkMsg50195462_;
        }
      }
      /**
       * <code>.UnkMsg50195462 unkMsg50195462 = 50195462;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          UnkMsg50195462, UnkMsg50195462.Builder, UnkMsg50195462OrBuilder>
          getUnkMsg50195462FieldBuilder() {
        if (unkMsg50195462Builder_ == null) {
          unkMsg50195462Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              UnkMsg50195462, UnkMsg50195462.Builder, UnkMsg50195462OrBuilder>(
                  getUnkMsg50195462(),
                  getParentForChildren(),
                  isClean());
          unkMsg50195462_ = null;
        }
        return unkMsg50195462Builder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UnkMsg49399797.UnkMsg49399797_1)
    }

    // @@protoc_insertion_point(class_scope:UnkMsg49399797.UnkMsg49399797_1)
    private static final UnkMsg49399797_1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UnkMsg49399797_1();
    }

    public static UnkMsg49399797_1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UnkMsg49399797_1>
        PARSER = new com.google.protobuf.AbstractParser<UnkMsg49399797_1>() {
      @Override
      public UnkMsg49399797_1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UnkMsg49399797_1> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UnkMsg49399797_1> getParserForType() {
      return PARSER;
    }

    @Override
    public UnkMsg49399797_1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int UNKMSG1_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<UnkMsg49399797_1> unkMsg1_;
  /**
   * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
   */
  @Override
  public java.util.List<UnkMsg49399797_1> getUnkMsg1List() {
    return unkMsg1_;
  }
  /**
   * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
   */
  @Override
  public java.util.List<? extends UnkMsg49399797_1OrBuilder>
      getUnkMsg1OrBuilderList() {
    return unkMsg1_;
  }
  /**
   * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
   */
  @Override
  public int getUnkMsg1Count() {
    return unkMsg1_.size();
  }
  /**
   * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
   */
  @Override
  public UnkMsg49399797_1 getUnkMsg1(int index) {
    return unkMsg1_.get(index);
  }
  /**
   * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
   */
  @Override
  public UnkMsg49399797_1OrBuilder getUnkMsg1OrBuilder(
      int index) {
    return unkMsg1_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < unkMsg1_.size(); i++) {
      output.writeMessage(1, unkMsg1_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < unkMsg1_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, unkMsg1_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof UnkMsg49399797)) {
      return super.equals(obj);
    }
    UnkMsg49399797 other = (UnkMsg49399797) obj;

    if (!getUnkMsg1List()
        .equals(other.getUnkMsg1List())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUnkMsg1Count() > 0) {
      hash = (37 * hash) + UNKMSG1_FIELD_NUMBER;
      hash = (53 * hash) + getUnkMsg1List().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static UnkMsg49399797 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UnkMsg49399797 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UnkMsg49399797 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UnkMsg49399797 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UnkMsg49399797 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UnkMsg49399797 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UnkMsg49399797 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UnkMsg49399797 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static UnkMsg49399797 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static UnkMsg49399797 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static UnkMsg49399797 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UnkMsg49399797 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(UnkMsg49399797 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UnkMsg49399797}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UnkMsg49399797)
      UnkMsg49399797OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return YTVideoComments.internal_static_UnkMsg49399797_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return YTVideoComments.internal_static_UnkMsg49399797_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UnkMsg49399797.class, Builder.class);
    }

    // Construct using icu.freedomintrovert.YTSendCommAntiFraud.grpcApi.UnkMsg49399797.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (unkMsg1Builder_ == null) {
        unkMsg1_ = java.util.Collections.emptyList();
      } else {
        unkMsg1_ = null;
        unkMsg1Builder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return YTVideoComments.internal_static_UnkMsg49399797_descriptor;
    }

    @Override
    public UnkMsg49399797 getDefaultInstanceForType() {
      return UnkMsg49399797.getDefaultInstance();
    }

    @Override
    public UnkMsg49399797 build() {
      UnkMsg49399797 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public UnkMsg49399797 buildPartial() {
      UnkMsg49399797 result = new UnkMsg49399797(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(UnkMsg49399797 result) {
      if (unkMsg1Builder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          unkMsg1_ = java.util.Collections.unmodifiableList(unkMsg1_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.unkMsg1_ = unkMsg1_;
      } else {
        result.unkMsg1_ = unkMsg1Builder_.build();
      }
    }

    private void buildPartial0(UnkMsg49399797 result) {
      int from_bitField0_ = bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof UnkMsg49399797) {
        return mergeFrom((UnkMsg49399797)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(UnkMsg49399797 other) {
      if (other == UnkMsg49399797.getDefaultInstance()) return this;
      if (unkMsg1Builder_ == null) {
        if (!other.unkMsg1_.isEmpty()) {
          if (unkMsg1_.isEmpty()) {
            unkMsg1_ = other.unkMsg1_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUnkMsg1IsMutable();
            unkMsg1_.addAll(other.unkMsg1_);
          }
          onChanged();
        }
      } else {
        if (!other.unkMsg1_.isEmpty()) {
          if (unkMsg1Builder_.isEmpty()) {
            unkMsg1Builder_.dispose();
            unkMsg1Builder_ = null;
            unkMsg1_ = other.unkMsg1_;
            bitField0_ = (bitField0_ & ~0x00000001);
            unkMsg1Builder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUnkMsg1FieldBuilder() : null;
          } else {
            unkMsg1Builder_.addAllMessages(other.unkMsg1_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              UnkMsg49399797_1 m =
                  input.readMessage(
                      UnkMsg49399797_1.parser(),
                      extensionRegistry);
              if (unkMsg1Builder_ == null) {
                ensureUnkMsg1IsMutable();
                unkMsg1_.add(m);
              } else {
                unkMsg1Builder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<UnkMsg49399797_1> unkMsg1_ =
      java.util.Collections.emptyList();
    private void ensureUnkMsg1IsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        unkMsg1_ = new java.util.ArrayList<UnkMsg49399797_1>(unkMsg1_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        UnkMsg49399797_1, UnkMsg49399797_1.Builder, UnkMsg49399797_1OrBuilder> unkMsg1Builder_;

    /**
     * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
     */
    public java.util.List<UnkMsg49399797_1> getUnkMsg1List() {
      if (unkMsg1Builder_ == null) {
        return java.util.Collections.unmodifiableList(unkMsg1_);
      } else {
        return unkMsg1Builder_.getMessageList();
      }
    }
    /**
     * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
     */
    public int getUnkMsg1Count() {
      if (unkMsg1Builder_ == null) {
        return unkMsg1_.size();
      } else {
        return unkMsg1Builder_.getCount();
      }
    }
    /**
     * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
     */
    public UnkMsg49399797_1 getUnkMsg1(int index) {
      if (unkMsg1Builder_ == null) {
        return unkMsg1_.get(index);
      } else {
        return unkMsg1Builder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
     */
    public Builder setUnkMsg1(
        int index, UnkMsg49399797_1 value) {
      if (unkMsg1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUnkMsg1IsMutable();
        unkMsg1_.set(index, value);
        onChanged();
      } else {
        unkMsg1Builder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
     */
    public Builder setUnkMsg1(
        int index, UnkMsg49399797_1.Builder builderForValue) {
      if (unkMsg1Builder_ == null) {
        ensureUnkMsg1IsMutable();
        unkMsg1_.set(index, builderForValue.build());
        onChanged();
      } else {
        unkMsg1Builder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
     */
    public Builder addUnkMsg1(UnkMsg49399797_1 value) {
      if (unkMsg1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUnkMsg1IsMutable();
        unkMsg1_.add(value);
        onChanged();
      } else {
        unkMsg1Builder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
     */
    public Builder addUnkMsg1(
        int index, UnkMsg49399797_1 value) {
      if (unkMsg1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUnkMsg1IsMutable();
        unkMsg1_.add(index, value);
        onChanged();
      } else {
        unkMsg1Builder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
     */
    public Builder addUnkMsg1(
        UnkMsg49399797_1.Builder builderForValue) {
      if (unkMsg1Builder_ == null) {
        ensureUnkMsg1IsMutable();
        unkMsg1_.add(builderForValue.build());
        onChanged();
      } else {
        unkMsg1Builder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
     */
    public Builder addUnkMsg1(
        int index, UnkMsg49399797_1.Builder builderForValue) {
      if (unkMsg1Builder_ == null) {
        ensureUnkMsg1IsMutable();
        unkMsg1_.add(index, builderForValue.build());
        onChanged();
      } else {
        unkMsg1Builder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
     */
    public Builder addAllUnkMsg1(
        Iterable<? extends UnkMsg49399797_1> values) {
      if (unkMsg1Builder_ == null) {
        ensureUnkMsg1IsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, unkMsg1_);
        onChanged();
      } else {
        unkMsg1Builder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
     */
    public Builder clearUnkMsg1() {
      if (unkMsg1Builder_ == null) {
        unkMsg1_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        unkMsg1Builder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
     */
    public Builder removeUnkMsg1(int index) {
      if (unkMsg1Builder_ == null) {
        ensureUnkMsg1IsMutable();
        unkMsg1_.remove(index);
        onChanged();
      } else {
        unkMsg1Builder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
     */
    public UnkMsg49399797_1.Builder getUnkMsg1Builder(
        int index) {
      return getUnkMsg1FieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
     */
    public UnkMsg49399797_1OrBuilder getUnkMsg1OrBuilder(
        int index) {
      if (unkMsg1Builder_ == null) {
        return unkMsg1_.get(index);  } else {
        return unkMsg1Builder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
     */
    public java.util.List<? extends UnkMsg49399797_1OrBuilder>
         getUnkMsg1OrBuilderList() {
      if (unkMsg1Builder_ != null) {
        return unkMsg1Builder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(unkMsg1_);
      }
    }
    /**
     * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
     */
    public UnkMsg49399797_1.Builder addUnkMsg1Builder() {
      return getUnkMsg1FieldBuilder().addBuilder(
          UnkMsg49399797_1.getDefaultInstance());
    }
    /**
     * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
     */
    public UnkMsg49399797_1.Builder addUnkMsg1Builder(
        int index) {
      return getUnkMsg1FieldBuilder().addBuilder(
          index, UnkMsg49399797_1.getDefaultInstance());
    }
    /**
     * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
     */
    public java.util.List<UnkMsg49399797_1.Builder>
         getUnkMsg1BuilderList() {
      return getUnkMsg1FieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        UnkMsg49399797_1, UnkMsg49399797_1.Builder, UnkMsg49399797_1OrBuilder>
        getUnkMsg1FieldBuilder() {
      if (unkMsg1Builder_ == null) {
        unkMsg1Builder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            UnkMsg49399797_1, UnkMsg49399797_1.Builder, UnkMsg49399797_1OrBuilder>(
                unkMsg1_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        unkMsg1_ = null;
      }
      return unkMsg1Builder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UnkMsg49399797)
  }

  // @@protoc_insertion_point(class_scope:UnkMsg49399797)
  private static final UnkMsg49399797 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new UnkMsg49399797();
  }

  public static UnkMsg49399797 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UnkMsg49399797>
      PARSER = new com.google.protobuf.AbstractParser<UnkMsg49399797>() {
    @Override
    public UnkMsg49399797 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UnkMsg49399797> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<UnkMsg49399797> getParserForType() {
    return PARSER;
  }

  @Override
  public UnkMsg49399797 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

