// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoComments.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

public interface UnkMsg49399797OrBuilder extends
    // @@protoc_insertion_point(interface_extends:UnkMsg49399797)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
   */
  java.util.List<UnkMsg49399797.UnkMsg49399797_1>
      getUnkMsg1List();
  /**
   * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
   */
  UnkMsg49399797.UnkMsg49399797_1 getUnkMsg1(int index);
  /**
   * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
   */
  int getUnkMsg1Count();
  /**
   * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
   */
  java.util.List<? extends UnkMsg49399797.UnkMsg49399797_1OrBuilder>
      getUnkMsg1OrBuilderList();
  /**
   * <code>repeated .UnkMsg49399797.UnkMsg49399797_1 unkMsg1 = 1;</code>
   */
  UnkMsg49399797.UnkMsg49399797_1OrBuilder getUnkMsg1OrBuilder(
      int index);
}
