// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoComments.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uid = 1;</code>
   * @return The uid.
   */
  String getUid();
  /**
   * <code>string uid = 1;</code>
   * @return The bytes for uid.
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>string uAT = 2;</code>
   * @return The uAT.
   */
  String getUAT();
  /**
   * <code>string uAT = 2;</code>
   * @return The bytes for uAT.
   */
  com.google.protobuf.ByteString
      getUATBytes();

  /**
   * <code>string avatarUrl = 3;</code>
   * @return The avatarUrl.
   */
  String getAvatarUrl();
  /**
   * <code>string avatarUrl = 3;</code>
   * @return The bytes for avatarUrl.
   */
  com.google.protobuf.ByteString
      getAvatarUrlBytes();
}
