// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoComments.proto

package icu.freedomintrovert.YTSendCommAntiFraud.grpcApi;

public interface VideoCommentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VideoCommentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ContinuationItemsAction777 ContinuationItemsAction = 777;</code>
   * @return Whether the continuationItemsAction field is set.
   */
  boolean hasContinuationItemsAction();
  /**
   * <code>.ContinuationItemsAction777 ContinuationItemsAction = 777;</code>
   * @return The continuationItemsAction.
   */
  ContinuationItemsAction777 getContinuationItemsAction();
  /**
   * <code>.ContinuationItemsAction777 ContinuationItemsAction = 777;</code>
   */
  ContinuationItemsAction777OrBuilder getContinuationItemsActionOrBuilder();

  /**
   * <code>.NextInfo8 nextInfo8 = 8;</code>
   * @return Whether the nextInfo8 field is set.
   */
  boolean hasNextInfo8();
  /**
   * <code>.NextInfo8 nextInfo8 = 8;</code>
   * @return The nextInfo8.
   */
  NextInfo8 getNextInfo8();
  /**
   * <code>.NextInfo8 nextInfo8 = 8;</code>
   */
  NextInfo8OrBuilder getNextInfo8OrBuilder();
}
